import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/db";

// Complete lender database with matching criteria
const SEED_LENDERS = [
  // ── Tier 1 — A Paper (650+ credit, established businesses) ──────────
  {
    name: "OnDeck",
    tier: 1,
    products: ["Working Capital", "Term Loan", "Line of Credit"],
    min_credit_score: 625,
    min_monthly_revenue: 10000,
    max_amount: 500000,
    min_time_in_business_months: 12,
    max_negative_days: 3,
    response_time_days: 1,
    submission_method: "portal" as const,
    portal_url: "https://www.ondeck.com/partners",
    notes: "Top-tier direct lender, large volume. Term loans 3-36mo, LOC up to $100K. Factor rates 1.03-1.35. Requires 1yr+ TIB.",
  },
  {
    name: "Credibly",
    tier: 1,
    products: ["Working Capital", "Line of Credit", "Revenue Based"],
    min_credit_score: 550,
    min_monthly_revenue: 15000,
    max_amount: 600000,
    min_time_in_business_months: 6,
    max_negative_days: 5,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@credibly.com",
    notes: "Easy docs, fast approval. WC $5K-$600K. Factor rates 1.10-1.45. Very broker-friendly. Same-day funding available.",
  },
  {
    name: "Fora Financial",
    tier: 1,
    products: ["Working Capital", "Term Loan"],
    min_credit_score: 550,
    min_monthly_revenue: 12000,
    max_amount: 1500000,
    min_time_in_business_months: 6,
    max_negative_days: 5,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@forafinancial.com",
    notes: "Up to $1.5M, established 2008. Short-term loans 5-15mo. Factor rates 1.15-1.50. Strong reputation, very broker-friendly.",
  },
  {
    name: "Kapitus",
    tier: 1,
    products: ["Working Capital", "Revenue Based", "Equipment Financing", "SBA Loan", "Line of Credit"],
    min_credit_score: 600,
    min_monthly_revenue: 15000,
    max_amount: 500000,
    min_time_in_business_months: 12,
    max_negative_days: 3,
    response_time_days: 2,
    submission_method: "email" as const,
    submission_email: "isosubmissions@kapitus.com",
    notes: "Multi-product lender since 2006. Has sales team. Equipment up to $2M. SBA 7(a) and 504. LOC $10K-$250K.",
  },
  {
    name: "Rapid Finance",
    tier: 1,
    products: ["Working Capital", "SBA Loan", "Line of Credit", "Equipment Financing", "Invoice Factoring"],
    min_credit_score: 580,
    min_monthly_revenue: 10000,
    max_amount: 1000000,
    min_time_in_business_months: 12,
    max_negative_days: 5,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@rapidfinance.com",
    notes: "Multi-product since 2005. WC $5K-$1M. Equipment up to $2M. Factoring for B2B. Fast decisions, same-day possible.",
  },
  {
    name: "Mulligan Funding",
    tier: 1,
    products: ["Working Capital", "Term Loan"],
    min_credit_score: 600,
    min_monthly_revenue: 15000,
    max_amount: 500000,
    min_time_in_business_months: 12,
    max_negative_days: 3,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@mulliganfunding.com",
    notes: "Strong A paper funder since 2008. Known for large advances and competitive rates. Prefers 1yr+ TIB.",
  },
  {
    name: "Wall Street Funding",
    tier: 1,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 620,
    min_monthly_revenue: 15000,
    max_amount: 500000,
    min_time_in_business_months: 12,
    max_negative_days: 3,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@wallstreetfunding.com",
    notes: "A paper, competitive rates. Fast approvals. Prefers clean bank statements, strong revenue.",
  },
  {
    name: "Idea Financial",
    tier: 1,
    products: ["Line of Credit"],
    min_credit_score: 650,
    min_monthly_revenue: 15000,
    max_amount: 275000,
    min_time_in_business_months: 24,
    max_negative_days: 0,
    response_time_days: 2,
    submission_method: "email" as const,
    submission_email: "partners@ideafinancial.com",
    notes: "LOC specialist. Revolving credit lines $25K-$275K. Rates from 15% APR. Strict on credit and TIB. True LOC product.",
  },
  {
    name: "CAN Capital",
    tier: 1,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 550,
    min_monthly_revenue: 8000,
    max_amount: 500000,
    min_time_in_business_months: 12,
    max_negative_days: 5,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@cancapital.com",
    notes: "One of the oldest MCA providers, founded 1998. WC and RBF. Fast, reliable, good for established businesses.",
  },
  {
    name: "Libertas Funding",
    tier: 1,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 600,
    min_monthly_revenue: 15000,
    max_amount: 500000,
    min_time_in_business_months: 12,
    max_negative_days: 3,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@libertasfunding.com",
    notes: "Greenwich CT. A paper MCA/RBF. Competitive factor rates. Known for clean deals and fast funding.",
  },
  {
    name: "BlueVine",
    tier: 1,
    products: ["Line of Credit"],
    min_credit_score: 650,
    min_monthly_revenue: 10000,
    max_amount: 250000,
    min_time_in_business_months: 24,
    max_negative_days: 0,
    response_time_days: 1,
    submission_method: "portal" as const,
    portal_url: "https://www.bluevine.com/partners",
    notes: "LOC specialist. Revolving lines up to $250K. A paper only. Must have 650+ credit and 2yr+ TIB. Weekly/monthly repayment.",
  },
  {
    name: "Lendr",
    tier: 1,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 620,
    min_monthly_revenue: 25000,
    max_amount: 1000000,
    min_time_in_business_months: 12,
    max_negative_days: 3,
    response_time_days: 2,
    submission_method: "email" as const,
    submission_email: "submissions@lendr.com",
    notes: "$250K+ advances, customized terms. Stricter requirements but larger amounts. Great for strong A paper deals.",
  },
  {
    name: "Super G Capital",
    tier: 1,
    products: ["Working Capital", "Term Loan"],
    min_credit_score: 600,
    min_monthly_revenue: 15000,
    max_amount: 500000,
    min_time_in_business_months: 12,
    max_negative_days: 5,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "funding@supergcapital.com",
    notes: "A-B paper. Term loans and WC. Fast decisions, same-day funding possible.",
  },

  // ── Tier 2 — B Paper (550-649 credit, 6mo+ TIB) ──────────────────
  {
    name: "Forward Financing",
    tier: 2,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 500,
    min_monthly_revenue: 10000,
    max_amount: 400000,
    min_time_in_business_months: 6,
    max_negative_days: 8,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@forwardfinancing.com",
    notes: "4.9/5 Trustpilot. World-class support, same-day funding. Accepts lower credit. Factor rates 1.15-1.50. Very broker-friendly.",
  },
  {
    name: "Vox Funding",
    tier: 2,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 525,
    min_monthly_revenue: 10000,
    max_amount: 500000,
    min_time_in_business_months: 6,
    max_negative_days: 8,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@voxfunding.com",
    notes: "B paper direct funder. Solid middle-market. Good for 550-620 credit range. Fast approvals.",
  },
  {
    name: "Fundworks",
    tier: 2,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 525,
    min_monthly_revenue: 8000,
    max_amount: 300000,
    min_time_in_business_months: 6,
    max_negative_days: 10,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@fundworks.com",
    notes: "B paper direct funder. Flexible on bank statements. Good for deals with some negatives.",
  },
  {
    name: "Greenbox Capital",
    tier: 2,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 500,
    min_monthly_revenue: 8000,
    max_amount: 500000,
    min_time_in_business_months: 6,
    max_negative_days: 10,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@greenboxcapital.com",
    notes: "B paper. Up to $500K. Flexible underwriting. Good for mid-range deals.",
  },
  {
    name: "Reliant Funding",
    tier: 2,
    products: ["Working Capital"],
    min_credit_score: 525,
    min_monthly_revenue: 8000,
    max_amount: 400000,
    min_time_in_business_months: 6,
    max_negative_days: 8,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@reliantfunding.com",
    notes: "$5K-$400K, same-day possible. B paper. Strong in retail and restaurant sectors.",
  },
  {
    name: "Balboa Capital",
    tier: 2,
    products: ["Working Capital", "Equipment Financing"],
    min_credit_score: 550,
    min_monthly_revenue: 10000,
    max_amount: 500000,
    min_time_in_business_months: 12,
    max_negative_days: 5,
    response_time_days: 2,
    submission_method: "email" as const,
    submission_email: "submissions@balboacapital.com",
    notes: "Equipment financing $10K-$500K. WC also available. Good for equipment-heavy businesses.",
  },
  {
    name: "Pearl Capital",
    tier: 2,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 500,
    min_monthly_revenue: 8000,
    max_amount: 500000,
    min_time_in_business_months: 4,
    max_negative_days: 10,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@pearlcapital.com",
    notes: "B-C paper direct funder. Lower TIB requirements (4mo). Good for newer businesses with revenue.",
  },
  {
    name: "SOS Capital",
    tier: 2,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 525,
    min_monthly_revenue: 10000,
    max_amount: 400000,
    min_time_in_business_months: 6,
    max_negative_days: 8,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@soscapital.com",
    notes: "Solid mid-tier. Reliable approvals in B paper range.",
  },
  {
    name: "VitalCap",
    tier: 2,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 525,
    min_monthly_revenue: 10000,
    max_amount: 400000,
    min_time_in_business_months: 6,
    max_negative_days: 8,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@vitalcap.com",
    notes: "Frequently recommended. Good broker relationships. Fast turnaround.",
  },
  {
    name: "Knight Capital",
    tier: 2,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 525,
    min_monthly_revenue: 10000,
    max_amount: 500000,
    min_time_in_business_months: 6,
    max_negative_days: 8,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@knightcapitalfunding.com",
    notes: "Active direct funder. Competitive B paper rates.",
  },
  {
    name: "Snap Advances",
    tier: 2,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 500,
    min_monthly_revenue: 8000,
    max_amount: 400000,
    min_time_in_business_months: 6,
    max_negative_days: 10,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@snapadvances.com",
    notes: "A-C paper, fast turnaround. Wide credit range acceptance. Very broker-friendly.",
  },
  {
    name: "Smart Business Funder",
    tier: 2,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 500,
    min_monthly_revenue: 8000,
    max_amount: 500000,
    min_time_in_business_months: 6,
    max_negative_days: 10,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@smartbusinessfunder.com",
    notes: "A-C paper, well-regarded. Flexible underwriting criteria.",
  },
  {
    name: "Capybara Capital",
    tier: 2,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 525,
    min_monthly_revenue: 15000,
    max_amount: 750000,
    min_time_in_business_months: 6,
    max_negative_days: 8,
    response_time_days: 2,
    submission_method: "email" as const,
    submission_email: "submissions@capybaracapital.com",
    notes: "A- to C+ paper, larger amounts, longer terms. Good for mid-market $100K+ deals.",
  },
  {
    name: "Hunter Capital",
    tier: 2,
    products: ["Working Capital"],
    min_credit_score: 525,
    min_monthly_revenue: 8000,
    max_amount: 300000,
    min_time_in_business_months: 6,
    max_negative_days: 8,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@huntercapitalgroup.com",
    notes: "B paper WC specialist. Quick decisions.",
  },
  {
    name: "Legend Funding",
    tier: 2,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 525,
    min_monthly_revenue: 8000,
    max_amount: 400000,
    min_time_in_business_months: 6,
    max_negative_days: 8,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@legendfunding.com",
    notes: "B paper direct funder. Reliable.",
  },
  {
    name: "Newco Capital",
    tier: 2,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 525,
    min_monthly_revenue: 10000,
    max_amount: 500000,
    min_time_in_business_months: 6,
    max_negative_days: 8,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@newcocap.com",
    notes: "B paper. Good volume capacity.",
  },
  {
    name: "Expansion Capital",
    tier: 2,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 525,
    min_monthly_revenue: 8000,
    max_amount: 400000,
    min_time_in_business_months: 6,
    max_negative_days: 8,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@expansioncap.com",
    notes: "B paper. Flexible on TIB and revenue.",
  },
  {
    name: "Cooper Capital",
    tier: 2,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 525,
    min_monthly_revenue: 8000,
    max_amount: 300000,
    min_time_in_business_months: 6,
    max_negative_days: 10,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@coopercapitalgroup.com",
    notes: "B paper specialist. Good for straightforward WC deals.",
  },
  {
    name: "Unique Funding Solutions",
    tier: 2,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 525,
    min_monthly_revenue: 8000,
    max_amount: 500000,
    min_time_in_business_months: 6,
    max_negative_days: 8,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@uniquefundingsolutions.com",
    notes: "UFS. B paper. Solid relationships.",
  },
  {
    name: "Bespoke Capital",
    tier: 2,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 525,
    min_monthly_revenue: 10000,
    max_amount: 500000,
    min_time_in_business_months: 6,
    max_negative_days: 8,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@bespokecapitalgroup.com",
    notes: "B paper. Competitive rates for qualified deals.",
  },
  {
    name: "Strategic Capital",
    tier: 2,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 500,
    min_monthly_revenue: 8000,
    max_amount: 500000,
    min_time_in_business_months: 6,
    max_negative_days: 10,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@strategiccap.com",
    notes: "A-C paper. Wide range acceptance.",
  },
  {
    name: "Square Capital",
    tier: 2,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 550,
    min_monthly_revenue: 10000,
    max_amount: 250000,
    min_time_in_business_months: 12,
    max_negative_days: 5,
    response_time_days: 1,
    submission_method: "portal" as const,
    portal_url: "https://squareup.com/capital",
    notes: "A-B paper, automated underwriting. Portal-only, requires Square processing history. Good for retail/food.",
  },

  // ── Tier 3 — High Risk (500+ credit, newer businesses, negatives OK) ──
  {
    name: "CFG Merchant Solutions",
    tier: 3,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 480,
    min_monthly_revenue: 8000,
    max_amount: 500000,
    min_time_in_business_months: 4,
    max_negative_days: 15,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@cfgms.com",
    notes: "High risk direct funder. Accepts negatives, lower credit. Factor rates 1.25-1.65. Fast decisions.",
  },
  {
    name: "Bitty Advance",
    tier: 3,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 450,
    min_monthly_revenue: 5000,
    max_amount: 100000,
    min_time_in_business_months: 3,
    max_negative_days: 20,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@bittyadvance.com",
    notes: "High risk, smaller advances $5K-$100K. Very low minimums. Good for stacking or first-position on weak deals.",
  },
  {
    name: "Lendini",
    tier: 3,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 480,
    min_monthly_revenue: 8000,
    max_amount: 250000,
    min_time_in_business_months: 4,
    max_negative_days: 15,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@lendini.com",
    notes: "High risk. Flexible on negatives. Quick approvals.",
  },
  {
    name: "Arsenal Business Capital",
    tier: 3,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 475,
    min_monthly_revenue: 8000,
    max_amount: 300000,
    min_time_in_business_months: 4,
    max_negative_days: 15,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@arsenalbc.com",
    notes: "High risk. Good for deals with existing positions.",
  },
  {
    name: "Splash Advance",
    tier: 3,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 480,
    min_monthly_revenue: 8000,
    max_amount: 400000,
    min_time_in_business_months: 4,
    max_negative_days: 15,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@splashadvance.com",
    notes: "A-C paper, high risk tier. Wider range of deal sizes.",
  },
  {
    name: "LCF (Light Capital Funding)",
    tier: 3,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 475,
    min_monthly_revenue: 8000,
    max_amount: 150000,
    min_time_in_business_months: 3,
    max_negative_days: 20,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@lcfunding.com",
    notes: "30-day terms, higher factors. Short-term, fast-turn deals. Good for urgent cash needs.",
  },
  {
    name: "Everest Business Funding",
    tier: 3,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 480,
    min_monthly_revenue: 10000,
    max_amount: 500000,
    min_time_in_business_months: 6,
    max_negative_days: 12,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@everestbusinessfunding.com",
    notes: "80-100 day terms. Higher factor rates but larger amounts available for high risk.",
  },
  {
    name: "YSC Funding",
    tier: 3,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 475,
    min_monthly_revenue: 8000,
    max_amount: 250000,
    min_time_in_business_months: 4,
    max_negative_days: 15,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@yscfunding.com",
    notes: "High risk direct. Quick approvals for subprime deals.",
  },
  {
    name: "Mantis Funding",
    tier: 3,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 480,
    min_monthly_revenue: 8000,
    max_amount: 300000,
    min_time_in_business_months: 4,
    max_negative_days: 15,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@mantisfunding.com",
    notes: "High risk. Reliable for C paper deals.",
  },
  {
    name: "Diverse Capital",
    tier: 3,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 475,
    min_monthly_revenue: 8000,
    max_amount: 300000,
    min_time_in_business_months: 4,
    max_negative_days: 15,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@diversecapitalinc.com",
    notes: "High risk. Accepts most industries.",
  },
  {
    name: "Thor Capital",
    tier: 3,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 475,
    min_monthly_revenue: 8000,
    max_amount: 300000,
    min_time_in_business_months: 4,
    max_negative_days: 15,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@thorcapitalgroup.com",
    notes: "High risk. Fast decisions.",
  },
  {
    name: "Proventure Capital",
    tier: 3,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 475,
    min_monthly_revenue: 8000,
    max_amount: 200000,
    min_time_in_business_months: 3,
    max_negative_days: 20,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@proventurecapital.com",
    notes: "40 days and under terms. Very short-term, high risk. Fast funding.",
  },
  {
    name: "Lionheart Business Capital",
    tier: 3,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 475,
    min_monthly_revenue: 8000,
    max_amount: 250000,
    min_time_in_business_months: 4,
    max_negative_days: 15,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@lionheartbc.com",
    notes: "40-week max terms. Subprime specialist.",
  },
  {
    name: "Arya Funding",
    tier: 3,
    products: ["Working Capital", "Revenue Based"],
    min_credit_score: 475,
    min_monthly_revenue: 8000,
    max_amount: 300000,
    min_time_in_business_months: 4,
    max_negative_days: 15,
    response_time_days: 1,
    submission_method: "email" as const,
    submission_email: "submissions@aryafunding.com",
    notes: "30-180 day deals. Flexible on terms and credit. Good last resort option.",
  },
  {
    name: "Lendio",
    tier: 3,
    products: ["Working Capital", "Term Loan", "Line of Credit", "SBA Loan"],
    min_credit_score: 500,
    min_monthly_revenue: 8000,
    max_amount: 500000,
    min_time_in_business_months: 6,
    max_negative_days: 10,
    response_time_days: 2,
    submission_method: "portal" as const,
    portal_url: "https://www.lendio.com/partners",
    notes: "Marketplace, works with lower credit. Matches to 75+ lenders. Portal submission. Good for hard-to-place deals.",
  },
];

export async function POST() {
  try {
    // Get existing lender names to avoid duplicates
    const { data: existing } = await supabaseAdmin
      .from("lenders")
      .select("name");
    const existingNames = new Set((existing || []).map((l: { name: string }) => l.name.toLowerCase()));

    const toInsert = SEED_LENDERS
      .filter((l) => !existingNames.has(l.name.toLowerCase()))
      .map((l) => ({
        name: l.name,
        tier: l.tier,
        products: l.products,
        notes: l.notes,
        min_credit_score: l.min_credit_score,
        min_monthly_revenue: l.min_monthly_revenue,
        max_amount: l.max_amount,
        min_time_in_business_months: l.min_time_in_business_months,
        max_negative_days: l.max_negative_days,
        response_time_days: l.response_time_days,
        submission_method: l.submission_method,
        submission_email: "submission_email" in l ? l.submission_email : null,
        portal_url: "portal_url" in l ? l.portal_url : null,
        is_active: true,
        blocked_industries: [],
      }));

    if (toInsert.length === 0) {
      return NextResponse.json({ message: "All lenders already exist.", added: 0 });
    }

    const { error } = await supabaseAdmin.from("lenders").insert(toInsert);

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({
      message: `Seeded ${toInsert.length} lenders (${SEED_LENDERS.length - toInsert.length} already existed).`,
      added: toInsert.length,
      skipped: SEED_LENDERS.length - toInsert.length,
    });
  } catch (err) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Seed failed" },
      { status: 500 }
    );
  }
}
