"use client";

// The map. Inline SVG, no mapping library, no tiles.
//
// ‼️ A CLIENT COMPONENT FOR ONE REASON: THE ZOOM. Everything else on the territory page is a server
// read and stays one. The zoom is a viewBox the person moves, and the decisions it serves are
// different at each end: nationally "which city next", inside a metro "which part of this one is
// unworked". A page that could only answer one of those would be the wrong page.
//
// ‼️ THE DOTS ARE REAL POSITIONS, NOT A CHOROPLETH. A state fill answers "has this state been
// touched", which is already answered by the table. Dots answer "this cluster of six clinics in
// north Dallas has nobody in it", which is a different and more useful question, and it is only
// possible because latitude and longitude were lifted into columns in Phase 1.
//
// ‼️ AND THE STATE OUTLINES ARE PRE-PROJECTED. src/data/us-outline.ts holds each state as one `d`
// string already in this viewBox, generated by scripts/_gen-us-outline.ts with the same `albers`
// this file projects dots through. One projection, used twice, so a dot cannot sit off its state.

import { useMemo, useState } from "react";
import { projectUs } from "@/lib/geo/us-albers";
import { US_FIT, US_STATES, US_VIEWBOX } from "@/data/us-outline";
import type { Stage, TerritoryDot } from "@/lib/scraper/territory";

/**
 * One colour per rung.
 *
 * ‼️ `call` IS ITS OWN COLOUR AND NOT A SHADE OF `dropped`, WHICH IS THE WHOLE POINT OF HAVING SIX.
 * 130 of the 550 stored leads are routed to a call and 108 of them have a phone number. Painting
 * those the same grey as a national chain location would hide 108 doors on a map whose only job is
 * showing where to go.
 *
 * ‼️ AND THE SCALE IS ORDERED, NOT CATEGORICAL. Furthest-reached is a ladder, so the colours run
 * warm (worked) to cool (untouched) rather than being six unrelated hues, and the two "nothing will
 * come of this" rungs are the only greys.
 */
const STAGE_STYLE: Record<Stage, { fill: string; label: string; note: string }> = {
  emailed: { fill: "#00C9A7", label: "handed off to send", note: "on a campaign, suppression knows them" },
  sendable: { fill: "#0E8C77", label: "address found", note: "verified and not yet handed off" },
  qualified: { fill: "#3B82F6", label: "qualified", note: "routed to enrichment, no address yet" },
  call: { fill: "#F59E0B", label: "call list", note: "real business, no address this lane can reach" },
  dropped: { fill: "#6B7280", label: "dropped", note: "chain, supplier or duplicate" },
  pulled: { fill: "#D1D5DB", label: "not judged yet", note: "pulled and waiting on qualification" },
};

/** Drawn last is drawn on top. Reversed from STAGES so `emailed` is never hidden under `pulled`. */
const PAINT_ORDER: Stage[] = ["pulled", "dropped", "call", "qualified", "sendable", "emailed"];

interface Props {
  dots: readonly TerritoryDot[];
  /** Per-state counts, keyed by the canonical full name, for the at-a-glance fill. */
  statePulled: Readonly<Record<string, number>>;
  /** True when territory_dots hit its row cap, so the map can say so rather than lying by omission. */
  capped: boolean;
}

export function TerritoryMap({ dots, statePulled, capped }: Props) {
  // The viewBox as four numbers. National is the generated frame; a zoom narrows it.
  // Annotated, because US_VIEWBOX is `as const` and its fields are the literal types 960 and 600:
  // inferred, this state could never hold a zoomed width.
  const [view, setView] = useState<{ x: number; y: number; w: number; h: number }>({
    x: 0,
    y: 0,
    w: US_VIEWBOX.width,
    h: US_VIEWBOX.height,
  });
  const [hover, setHover] = useState<{ x: number; y: number; text: string } | null>(null);

  const zoomed = view.w < US_VIEWBOX.width;

  const projected = useMemo(
    () =>
      dots
        .map((d) => {
          const p = projectUs(d.lat, d.lon, US_FIT);
          return p ? { ...d, ...p } : null;
        })
        // ‼️ AN UNPROJECTABLE DOT IS DROPPED, NEVER DRAWN AT 0,0. A lead just over the Canadian or
        // Mexican border has a real coordinate and no place in any of the three region boxes, and a
        // coerced zero would stack unrelated dots in the top-left corner where they read as a
        // cluster. The page reports the count separately.
        .filter((d): d is NonNullable<typeof d> => d !== null),
    [dots]
  );

  const unprojectable = dots.length - projected.length;

  // ‼️ THE RADIUS SCALES WITH THE ZOOM SO A DOT STAYS THE SAME SIZE ON SCREEN. The viewBox shrinks
  // and the browser scales everything inside it, including stroke widths and radii, so a 2px dot at
  // national zoom becomes a 16px blob at 8x. Dividing by the zoom factor holds it still.
  const zoom = US_VIEWBOX.width / view.w;
  const radiusOf = (n: number) => (Math.min(2 + Math.sqrt(n) * 0.9, 11) / zoom) * (zoomed ? 1.4 : 1);

  const maxPulled = Math.max(1, ...Object.values(statePulled));

  function zoomTo(cx: number, cy: number, factor: number) {
    const w = Math.min(US_VIEWBOX.width, Math.max(US_VIEWBOX.width / 14, view.w / factor));
    const h = w * (US_VIEWBOX.height / US_VIEWBOX.width);
    setView({
      // Clamped inside the frame, so a zoom near an edge cannot pan off the map into blank space.
      x: Math.max(0, Math.min(US_VIEWBOX.width - w, cx - w / 2)),
      y: Math.max(0, Math.min(US_VIEWBOX.height - h, cy - h / 2)),
      w,
      h,
    });
  }

  return (
    <div className="relative">
      <div className="mb-2 flex flex-wrap items-center gap-x-4 gap-y-1 text-xs">
        {PAINT_ORDER.slice()
          .reverse()
          .map((s) => (
            <span key={s} className="inline-flex items-center gap-1.5" title={STAGE_STYLE[s].note}>
              <span
                className="inline-block h-2.5 w-2.5 rounded-full"
                style={{ background: STAGE_STYLE[s].fill }}
              />
              <span className="text-gray-600">{STAGE_STYLE[s].label}</span>
            </span>
          ))}
        <span className="ml-auto flex items-center gap-2">
          {zoomed && (
            <button
              type="button"
              onClick={() => setView({ x: 0, y: 0, w: US_VIEWBOX.width, h: US_VIEWBOX.height })}
              className="rounded border border-gray-300 px-2 py-0.5 text-gray-700 hover:bg-gray-50"
            >
              Back to national
            </button>
          )}
          <span className="text-gray-400">
            {zoomed ? `${zoom.toFixed(1)}x  click to zoom in` : "click a cluster to zoom"}
          </span>
        </span>
      </div>

      <svg
        viewBox={`${view.x} ${view.y} ${view.w} ${view.h}`}
        className="w-full rounded-lg border border-gray-200 bg-[#F8FAFC]"
        style={{ aspectRatio: `${US_VIEWBOX.width} / ${US_VIEWBOX.height}` }}
        onDoubleClick={() => setView({ x: 0, y: 0, w: US_VIEWBOX.width, h: US_VIEWBOX.height })}
      >
        {/* The state layer. A pale fill proportional to leads pulled, which is the at-a-glance
            answer to "how much of the country has been touched at all". Deliberately pale: the dots
            are the data and a saturated choropleth would drown them. */}
        <g>
          {US_STATES.map((s) => {
            const n = statePulled[s.name] ?? 0;
            return (
              <path
                key={s.name}
                d={s.d}
                fill={n ? `rgba(14, 140, 119, ${0.08 + 0.3 * (n / maxPulled)})` : "#FFFFFF"}
                stroke="#CBD5E1"
                strokeWidth={0.7 / zoom}
                onMouseEnter={(e) =>
                  setHover({
                    x: e.nativeEvent.offsetX,
                    y: e.nativeEvent.offsetY,
                    text: `${s.name}: ${n.toLocaleString()} pulled`,
                  })
                }
                onMouseLeave={() => setHover(null)}
                onClick={() => zoomTo(s.labelX, s.labelY, 3)}
                style={{ cursor: "zoom-in" }}
              />
            );
          })}
        </g>

        {/* State labels, only at national zoom and only where there is something to report: a map
            with 51 abbreviations on it is less readable than one with four. */}
        {!zoomed && (
          <g pointerEvents="none">
            {US_STATES.filter((s) => (statePulled[s.name] ?? 0) > 0).map((s) => (
              <text
                key={s.name}
                x={s.labelX}
                y={s.labelY - 8}
                textAnchor="middle"
                className="fill-gray-700"
                style={{ fontSize: 11, fontWeight: 600 }}
              >
                {s.name}
              </text>
            ))}
          </g>
        )}

        {/* The dots, painted furthest-reached last so a worked lead is never hidden under an
            unjudged one sitting on the same block. */}
        {PAINT_ORDER.map((stage) => (
          <g key={stage}>
            {projected
              .filter((d) => d.stage === stage)
              .map((d, i) => (
                <circle
                  key={`${stage}-${i}`}
                  cx={d.x}
                  cy={d.y}
                  r={radiusOf(d.n)}
                  fill={STAGE_STYLE[stage].fill}
                  fillOpacity={0.78}
                  stroke="#FFFFFF"
                  strokeWidth={0.5 / zoom}
                  onMouseEnter={(e) =>
                    setHover({
                      x: e.nativeEvent.offsetX,
                      y: e.nativeEvent.offsetY,
                      text: `${d.n} ${STAGE_STYLE[stage].label}  ${d.lat.toFixed(2)}, ${d.lon.toFixed(2)}`,
                    })
                  }
                  onMouseLeave={() => setHover(null)}
                  onClick={() => zoomTo(d.x, d.y, 3)}
                  style={{ cursor: "zoom-in" }}
                />
              ))}
          </g>
        ))}
      </svg>

      {hover && (
        <div
          className="pointer-events-none absolute z-10 rounded bg-gray-900 px-2 py-1 text-xs text-white shadow"
          style={{ left: hover.x + 10, top: hover.y + 10 }}
        >
          {hover.text}
        </div>
      )}

      {/* ‼️ THE MAP SAYS WHAT IT IS NOT SHOWING. A capped or filtered map that looks complete is
          worse than one that admits a gap, because the decision it feeds is "where is unworked". */}
      {(capped || unprojectable > 0) && (
        <p className="mt-2 text-xs text-amber-700">
          {capped && `Showing the ${dots.length.toLocaleString()} largest clusters; the counts are complete but some dots are merged. `}
          {unprojectable > 0 &&
            `${unprojectable} cluster${unprojectable === 1 ? "" : "s"} sit outside the United States and are not drawn.`}
        </p>
      )}
    </div>
  );
}
