import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/db";
import { telegram } from "@/lib/telegram";
import { ALL_VERTICALS, AWARENESS_LEVELS } from "@/config/ads-verticals";
import { AD_GENERATION_PROMPT } from "@/config/meta-ads-system-prompt";

export const dynamic = "force-dynamic";

// Runs nightly at 11pm UTC (~6-7pm EST) via Vercel Cron
// Generates 100 ad ideas across verticals × awareness layers
export async function GET() {
  try {
    // 1. Fetch recent pipeline data for context
    const { data: rawPipelineData } = await supabaseAdmin
      .from("deals")
      .select("stage, amount, contacts(business_name)")
      .order("updated_at", { ascending: false })
      .limit(20);

    const pipelineData = (rawPipelineData || []).map((d) => {
      const c = d.contacts as unknown as { business_name: string } | null;
      return { business_name: c?.business_name || "Unknown", stage: d.stage, amount: d.amount };
    });

    const { data: recentLogs } = await supabaseAdmin
      .from("system_logs")
      .select("description, metadata")
      .in("event_type", ["daily_recap", "ad_approved"])
      .order("created_at", { ascending: false })
      .limit(10);

    // 2. Build context from pipeline + logs
    const pipelineContext = pipelineData
      ?.map((d) => `${d.business_name}: ${d.stage} ($${d.amount})`)
      .join(", ") || "No recent pipeline data";

    const logContext = recentLogs
      ?.map((l) => l.description)
      .join("; ") || "";

    // 3. Pick 10 random verticals for variety
    const shuffled = [...ALL_VERTICALS].sort(() => Math.random() - 0.5);
    const selectedVerticals = shuffled.slice(0, 10);
    const verticalNames = selectedVerticals.map((v) => v.name).join(", ");

    // 4. Call AI to generate 100 ad ideas (in batches if needed)
    let allIdeas: Array<{
      hook: string;
      primaryText: string;
      headline: string;
      vertical: string;
      layer: string;
      cta: string;
    }> = [];

    // Generate in 2 batches of 50
    for (let batch = 0; batch < 2; batch++) {
      const batchVerticals = batch === 0
        ? selectedVerticals.slice(0, 5).map((v) => v.name).join(", ")
        : selectedVerticals.slice(5, 10).map((v) => v.name).join(", ");
      const layerNames = AWARENESS_LEVELS.map((l) => l.label).join(", ");

      try {
        const res = await fetch(
          `${process.env.NEXT_PUBLIC_APP_URL || "https://mission-control.srtagency.com"}/api/chat`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              messages: [
                { role: "system", content: AD_GENERATION_PROMPT },
                {
                  role: "user",
                  content: `Generate 50 ad ideas across these verticals: ${batchVerticals}. Mix all 7 awareness levels (${layerNames}). Pipeline context: ${pipelineContext}. Recent activity: ${logContext}. Return a JSON array with: hook, primaryText, headline, vertical, layer, cta. No markdown.`,
                },
              ],
            }),
          }
        );

        if (res.ok) {
          const data = await res.json();
          const text = data.response || data.message || "";
          const match = text.match(/\[[\s\S]*\]/);
          if (match) {
            const parsed = JSON.parse(match[0]);
            allIdeas = [...allIdeas, ...parsed];
          }
        }
      } catch (e) {
        console.error(`Batch ${batch + 1} generation error:`, e);
      }
    }

    // 5. Store full results in system_logs
    await supabaseAdmin.from("system_logs").insert({
      event_type: "ad_intelligence",
      description: `Nightly ad intelligence: ${allIdeas.length} ideas generated across ${verticalNames}`,
      metadata: {
        ideas_count: allIdeas.length,
        verticals_used: selectedVerticals.map((v) => v.name),
        ideas: allIdeas.slice(0, 100), // Cap at 100
        pipeline_summary: pipelineContext,
        generated_at: new Date().toISOString(),
      },
    });

    // 6. Send top-10 summary to Telegram
    const chatId = process.env.TELEGRAM_CHAT_ID;
    if (telegram.isConfigured() && chatId) {
      const top10 = allIdeas.slice(0, 10);
      const lines: string[] = [
        "\uD83E\uDDE0 *Nightly Ad Intelligence Report*",
        "",
        `\uD83D\uDCA1 *${allIdeas.length} ad ideas generated*`,
        `\uD83C\uDFAF Verticals: ${verticalNames}`,
        "",
        "\uD83D\uDD1D *Top 10 Ideas:*",
        "",
      ];

      top10.forEach((idea, i) => {
        lines.push(`${i + 1}. *${idea.hook}*`);
        lines.push(`   ${idea.vertical} | ${idea.layer}`);
        lines.push(`   ${idea.primaryText?.slice(0, 100)}...`);
        lines.push("");
      });

      lines.push("_View all ideas in Mission Control > Marketing > Ad Intelligence_");
      lines.push("_Generated by Musa AI \u2014 SRT Mission Control_");

      await telegram.sendMessage(chatId, lines.join("\n"));
    }

    return NextResponse.json({
      success: true,
      ideas: allIdeas.length,
      verticals: selectedVerticals.map((v) => v.name),
      telegramSent: telegram.isConfigured() && !!chatId,
    });
  } catch (error) {
    console.error("Ad intelligence cron error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Ad intelligence failed" },
      { status: 500 }
    );
  }
}
