// Types for importing an image, committed because CI has no next-env.d.ts.
//
// ‼️ next-env.d.ts IS GENERATED BY `next dev` / `next build` AND IS GITIGNORED, so the typecheck in
// .github/workflows/checks.yml runs on a checkout where it does not exist. The mascot module
// (src/lib/concierge/mascot) imports .webp and .png files, which resolved locally and failed in CI with TS2307
// on 2026-09-16. This is the same reference next-env.d.ts carries; having it in the repo means the check that
// runs on a clean checkout sees what a developer sees.

/// <reference types="next/image-types/global" />
