import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/db";
import { telegram } from "@/lib/telegram";
import { generateDailyCalls, generateLeadMagnetIdeas } from "@/config/mock-calls";

// Runs daily at midnight UTC (7pm EST) via Vercel Cron
// Generates lead magnet ideas from call data and sends to Telegram + Supabase
export async function GET() {
  try {
    const calls = generateDailyCalls(10);
    const ideas = generateLeadMagnetIdeas(10);

    const hotLeads = calls.filter(
      (c) => c.outcome === "interested" || c.outcome === "applied"
    ).length;
    const totalRequested = calls.reduce((s, c) => s + c.requestedAmount, 0);
    const topIndustries = [...new Set(calls.map((c) => c.industry))].slice(0, 4);

    // Build Telegram message
    const lines: string[] = [
      "🔔 *Daily Call Recap & Lead Magnet Ideas*",
      "",
      `📞 *${calls.length} calls* today | 🔥 *${hotLeads} hot leads* | 💰 *$${totalRequested.toLocaleString()}* requested`,
      `📊 Top industries: ${topIndustries.join(", ")}`,
      "",
      "💡 *Today's Lead Magnet Ideas:*",
      "",
    ];

    ideas.forEach((idea, i) => {
      lines.push(
        `${i + 1}. *${idea.title}* [${idea.type.toUpperCase()}]`
      );
      lines.push(`   ${idea.description.slice(0, 120)}...`);
      lines.push(`   _${idea.industry} — ${idea.painPoint}_`);
      lines.push("");
    });

    lines.push("_Generated by Musa AI — SRT Mission Control_");

    const message = lines.join("\n");

    // Send to Telegram
    const chatId = process.env.TELEGRAM_CHAT_ID;
    if (telegram.isConfigured() && chatId) {
      await telegram.sendMessage(chatId, message);
    }

    // Save to Supabase for dashboard display
    await supabaseAdmin.from("system_logs").insert({
      event_type: "daily_recap",
      description: `Daily recap: ${calls.length} calls, ${hotLeads} hot leads, ${ideas.length} lead magnet ideas generated.`,
      metadata: {
        calls_count: calls.length,
        hot_leads: hotLeads,
        total_requested: totalRequested,
        top_industries: topIndustries,
        ideas: ideas.map((i) => ({ title: i.title, type: i.type, industry: i.industry })),
        generated_at: new Date().toISOString(),
      },
    });

    return NextResponse.json({
      success: true,
      calls: calls.length,
      hotLeads,
      totalRequested,
      ideas: ideas.length,
      telegramSent: telegram.isConfigured() && !!chatId,
    });
  } catch (error) {
    console.error("Daily recap cron error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Daily recap failed" },
      { status: 500 }
    );
  }
}
