// The measured half of the onboarding map: docs/ONBOARDING-MAP-MEASURED.md.
//
//   bunx tsx --env-file=.env.local scripts/_step-wiring.ts --live
//
// ‼️ THIS FILE IS THE ONLY PLACE THE MAP TOUCHES A DATABASE, AND ITS OUTPUT IS NEVER --check'ed.
// _step-wiring.ts builds two STATIC docs with synchronous functions and dynamically imports this
// one for --live. That split is the enforcement: a live number cannot reach a checked doc by
// accident, because you cannot read a database synchronously.
//
// ‼️ RESOLVED BY SLUG, NEVER A PINNED ID. SRT has been re-onboarded twice and every id written down
// for it in this repo is dead. A slug that does not resolve is an error, not a doc full of zeros:
// a map reporting "0 rows" for a client that does not exist reads exactly like a client with no
// data, and somebody would act on it.
//
// ‼️ EVERY NUMBER CARRIES THE SELECT THAT PRODUCED IT. D9: no number on a board the system did not
// measure. A count with its query beside it is a claim somebody can check; a bare count is not.

import { supabaseAdmin } from "@/lib/db";
import { DELIVERY_STEPS, stepNumber, type StepKey } from "@/config/delivery-steps";
import { leadContext, isHeld, ALL_SLICES } from "@/lib/clients/lead-context";
import { gapsFrom, gapLines } from "@/lib/clients/step-gaps";

const SLUG = "srt-agency-llc";

/**
 * Tables worth counting, with what each one being empty would mean.
 *
 * ‼️ THE KEY COLUMN IS DECLARED, NOT ASSUMED. `client_id` is not universal: avatar_briefs is keyed
 * on (vertical, avatar_slug) and carries `first_client_id`, because a brief belongs to an AVATAR
 * and is deliberately shared between clients. Filtering it by client_id selected a column that does
 * not exist, and one unknown column fails the whole PostgREST select, so the first run of this file
 * reported it unreadable. Declaring the key makes the shared table visibly shared instead.
 */
const COUNTED: ReadonlyArray<{ table: string; why: string; key?: string }> = [
  { table: "client_delivery_steps", why: "the board itself" },
  { table: "client_audiences", why: "who we are selling to" },
  { table: "client_offers", why: "what is being sold" },
  { table: "audience_documents", why: "the framework documents: sheet, offer, beliefs, ladder" },
  { table: "avatar_briefs", why: "shared research per avatar, keyed on the avatar and NOT on this client", key: "first_client_id" },
  { table: "client_keywords", why: "the searches the pages answer" },
  { table: "client_headlines", why: "the headline each page promises" },
  { table: "page_plan", why: "the planned pages" },
  { table: "page_angles", why: "the idea behind each page" },
  { table: "client_pages", why: "pages that have actually been drafted" },
  { table: "page_dataset", why: "the training record of what was drafted" },
  { table: "page_plan_runs", why: "snapshots taken before a plan is replaced" },
  { table: "page_sources", why: "the evidence a page is allowed to cite" },
  { table: "page_gate_runs", why: "quality gate verdicts" },
  { table: "lead_magnets", why: "what the concierge hands over" },
  { table: "client_datasets", why: "every paid pull we hold for this lead" },
  { table: "client_events", why: "what has happened in this client's channel" },
];

const PAGE = 1000;

async function countFor(table: string, key: string, clientId: string): Promise<{ n: number | null; note: string }> {
  // ‼️ A REAL GET, NOT A HEAD. A HEAD against a table PostgREST does not know returns
  // {count: null, error: null}, which is indistinguishable from an empty table.
  // The key column is the one selected, so the select can never name a column that does not exist.
  const { data, error } = await supabaseAdmin.from(table).select(key).eq(key, clientId).limit(PAGE);
  if (error) return { n: null, note: `unreadable: ${error.message}` };
  return { n: data?.length ?? 0, note: `select ${key} from ${table} where ${key} = <this client> limit ${PAGE}` };
}

export async function measuredMap(): Promise<{ ok: true; body: string } | { ok: false; error: string }> {
  const { data: client, error } = await supabaseAdmin
    .from("clients")
    .select("id, slug, legal_name, website, vertical_slug")
    .eq("slug", SLUG)
    .maybeSingle();
  if (error) return { ok: false, error: `could not read clients: ${error.message}` };
  if (!client) {
    return {
      ok: false,
      error: `no client with slug "${SLUG}". Nothing was written: a map of zeros for a client that does not exist reads exactly like a client with no data.`,
    };
  }

  const today = new Date().toISOString().slice(0, 10);
  const ctx = await leadContext(client.id, { include: ALL_SLICES });

  const lines: string[] = [];
  lines.push(`# The onboarding map, measured ${today} against \`${client.slug}\``);
  lines.push("");
  lines.push(
    "**Generated by `bunx tsx --env-file=.env.local scripts/_step-wiring.ts --live`. Do not edit by hand, " +
      "and do not add it to the drift check:** every number here changes when production does."
  );
  lines.push("");
  lines.push(
    "Its static companion is `docs/ONBOARDING-MAP.md`, which says what each step needs and would ask. " +
      "This file says what this one client actually holds."
  );
  lines.push("");
  lines.push(`Client: **${client.legal_name}**, ${client.website ?? "no website on file"}, vertical \`${client.vertical_slug ?? "none"}\`.`);
  lines.push("");

  if (ctx.readErrors.length) {
    lines.push("## Reads that failed");
    lines.push("");
    lines.push("‼️ Every field below sourced from one of these is unknown, not absent.");
    lines.push("");
    for (const e of ctx.readErrors) lines.push(`- ${e}`);
    lines.push("");
  }

  lines.push("## What this client holds");
  lines.push("");
  lines.push("| table | rows | why it matters | the select |");
  lines.push("| --- | --- | --- | --- |");
  for (const { table, why, key } of COUNTED) {
    const got = await countFor(table, key ?? "client_id", client.id);
    const n = got.n === null ? "unreadable" : got.n === PAGE ? `${PAGE}+` : String(got.n);
    lines.push(`| \`${table}\` | ${n} | ${why} | \`${got.note}\` |`);
  }
  lines.push("");

  lines.push("## The board, as it stands");
  lines.push("");
  lines.push(`Cursor: ${isHeld(ctx.board.cursor) ? `**${stepNumber(ctx.board.cursor.value)}. \`${ctx.board.cursor.value}\`**` : "none reachable"}.`);
  lines.push("");
  lines.push("| # | step | status | verified by | completed |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (const s of ctx.board.steps) {
    lines.push(`| ${s.number} | \`${s.key}\` | ${s.status} | ${s.verifiedSource ?? "not verified"} | ${s.completedAt?.slice(0, 10) ?? "no"} |`);
  }
  lines.push("");

  lines.push("## What each step is still missing, on this client");
  lines.push("");
  lines.push("This is `gapLines()` against the real datasets, uncapped. A step that asks for nothing says so.");
  lines.push("");
  for (const step of DELIVERY_STEPS) {
    const key = step.key as StepKey;
    const g = gapsFrom(ctx, key);
    lines.push(`### ${stepNumber(key)}. \`${key}\``);
    lines.push("");
    lines.push("```");
    lines.push(gapLines(g, Infinity).join("\n"));
    lines.push("```");
    lines.push("");
  }

  return { ok: true, body: lines.join("\n") + "\n" };
}
