// One-shot: upsert all confirmed/active lenders into the Supabase lenders table.
// Run with: bun run scripts/upsert-confirmed-lenders.ts

import { supabaseAdmin } from "../src/lib/db";

const CONFIRMED_LENDERS = [
  {
    name: "VOX Funding",
    tier: 2,
    tier_label: "Tier B – Mid-Tier",
    is_active: true,
    submission_method: "email" as const,
    submission_email: "submissions@voxfunding.com",
    cc_emails: ["wdorsey@voxfunding.com"],
    rep_name: "William Dorsey",
    rep_email: "wdorsey@voxfunding.com",
    min_credit_score: 500,
    min_monthly_revenue: 10000,
    min_time_in_business_months: 6,
    max_amount: 500000,
    factor_rate_range: "1.15 - 1.50",
    positions_funded: "1st, 2nd",
    repayment_frequency: "Daily/Weekly",
    funding_speed: "24-48 hrs",
    notes: "Strong 2nd position funder. B-C paper. Quick turnaround on approvals. Already active pre-2026-03.",
  },
  {
    name: "Arsenal Funding",
    tier: 3,
    tier_label: "Tier C – Flexible",
    is_active: true,
    submission_method: "email" as const,
    submission_email: "subs@arsenalfunding.com",
    cc_emails: [],
    min_credit_score: 450,
    min_monthly_revenue: 7000,
    min_time_in_business_months: 4,
    max_amount: 250000,
    factor_rate_range: "1.25 - 1.50+",
    positions_funded: "1st thru 4th",
    repayment_frequency: "Daily",
    funding_speed: "24 hrs",
    notes: "C-D paper. Quick snap funding for smaller deals. Works deep positions. ISO agreement on file.",
  },
  {
    name: "Forward Financing",
    tier: 2,
    tier_label: "Tier B – Mid-Tier",
    is_active: true,
    submission_method: "portal" as const,
    portal_url: "https://brokers.forwardfinancing.com",
    cc_emails: [],
    rep_name: "Austin Kelley; Parker Richards",
    rep_email: "akelley@forwardfinancing.com",
    min_credit_score: 500,
    min_monthly_revenue: 10000,
    min_time_in_business_months: 12,
    max_amount: 600000,
    factor_rate_range: "1.15 - 1.50",
    positions_funded: "1st, 2nd",
    repayment_frequency: "Daily/Weekly",
    funding_speed: "Same day",
    notes: "Re-onboarded 2026-03-26. Great for bad credit merchants. Revenue-focused underwriting. 60% paydown for renewal. Est. 2012.",
  },
  {
    name: "Funderial",
    tier: 3,
    tier_label: "Tier C – Flexible",
    is_active: true,
    submission_method: "email" as const,
    submission_email: "subs@funderial.com",
    cc_emails: ["colton@funderial.com"],
    rep_name: "Colton Wilson",
    rep_email: "colton@funderial.com",
    min_credit_score: 450,
    min_monthly_revenue: 7000,
    min_time_in_business_months: 3,
    max_amount: 250000,
    factor_rate_range: "1.30 - 1.50+",
    positions_funded: "2nd thru 5th",
    repayment_frequency: "Daily",
    funding_speed: "24 hrs",
    notes: "Deep position specialist. C-D paper. Higher rates reflect risk. Fast approvals. ISO signed via Conga Sign 2026-03-02.",
  },
  {
    name: "NewCo Capital Group",
    tier: 2,
    tier_label: "Tier B – Mid-Tier",
    is_active: true,
    submission_method: "email" as const,
    submission_email: "submissions@newcocapitalgroup.com",
    cc_emails: ["sara@newcocapitalgroup.com", "Rebekah@newcocapitalgroup.com", "jennie@newcocapitalgroup.com"],
    rep_name: "Alan Miller; Jennie Villano",
    rep_email: "alan@newcocapitalgroup.com",
    min_credit_score: 500,
    min_monthly_revenue: 100000,
    min_time_in_business_months: 12,
    max_negative_days: 7,
    max_amount: 2000000,
    factor_rate_range: "1.15 - 1.50",
    positions_funded: "1st thru 4th",
    repayment_frequency: "Daily/Weekly",
    funding_speed: "24-48 hrs",
    notes: "A-B paper. Up to $2M / 12mo. 14 pts max commission. ≤7 neg/low balance days. Canada also available. ISO DocuSigned 2026-03-02. Also has Capytal arm (C-D paper, 2nd-7th pos, $75K+/mo rev, up to $250K, 12 pts max).",
  },
  {
    name: "Splash Advance",
    tier: 3,
    tier_label: "Tier C – Flexible",
    is_active: true,
    submission_method: "email" as const,
    submission_email: "TEAMKR@SPLASHADVANCE.COM",
    cc_emails: ["KR@SPLASHADVANCE.COM"],
    rep_name: "Kevin Richardson",
    rep_email: "kr@splashadvance.com",
    min_credit_score: 450,
    min_monthly_revenue: 7000,
    min_time_in_business_months: 4,
    max_amount: 500000,
    factor_rate_range: "1.20 - 1.50",
    positions_funded: "1st thru 3rd",
    repayment_frequency: "Daily/Weekly",
    funding_speed: "24-48 hrs",
    notes: "A-C paper. Works multiple positions. ISO signed via Adobe Sign 2026-03-03.",
  },
  {
    name: "Velocity Capital Group",
    tier: 2,
    tier_label: "Tier B – Mid-Tier",
    is_active: true,
    submission_method: "email" as const,
    submission_email: "",
    cc_emails: ["zach@velocitycg.com"],
    rep_name: "Zach Dupuy; Meira Shapiro",
    rep_email: "zach@velocitycg.com",
    min_credit_score: 500,
    min_monthly_revenue: 10000,
    min_time_in_business_months: 6,
    max_amount: 500000,
    factor_rate_range: "1.20 - 1.50",
    positions_funded: "1st, 2nd",
    repayment_frequency: "Daily/Weekly",
    funding_speed: "24-48 hrs",
    notes: "ISO DocuSigned + W-9 completed 2026-03-05. Contact Zach for submissions.",
  },
  {
    name: "Legend Advance Funding",
    tier: 2,
    tier_label: "Tier B – Mid-Tier",
    is_active: true,
    submission_method: "email" as const,
    submission_email: "apps@legendfunding.com",
    cc_emails: ["Lmoreno@legendfunding.com"],
    rep_name: "Lily Moreno",
    rep_email: "Lmoreno@legendfunding.com",
    min_credit_score: 500,
    min_monthly_revenue: 10000,
    min_time_in_business_months: 6,
    max_amount: 500000,
    factor_rate_range: "1.20 - 1.50",
    positions_funded: "1st, 2nd",
    repayment_frequency: "Daily/Weekly",
    funding_speed: "24-48 hrs",
    notes: "Officially approved as ISO Partner 2026-03-19. PDF attachments required. Known as strong 2nd position funder. B-C paper. Lily Moreno 754-220-5975.",
  },
  {
    name: "CFG Merchant Solutions",
    tier: 3,
    tier_label: "Tier C – Flexible",
    is_active: true,
    submission_method: "email" as const,
    submission_email: "GGGSubmissions@CFGMS.com",
    cc_emails: ["MRodriquez@CFGMS.com"],
    rep_name: "Moses Rodriguez",
    rep_email: "MRodriquez@CFGMS.com",
    min_credit_score: 450,
    min_monthly_revenue: 10000,
    min_time_in_business_months: 4,
    max_amount: 400000,
    factor_rate_range: "1.20 - 1.50+",
    positions_funded: "1st thru 4th",
    repayment_frequency: "Daily/Weekly",
    funding_speed: "24-48 hrs",
    blocked_industries: ["nonprofits"],
    notes: "B-D paper. $5K-$200K advances. Factor rates as low as 1.3s. Next-day commissions. No defaults, nonprofits, or reverses. No 1st pos trucking/construction unless >$50K/mo. Moses Rodriguez 212-444-7680. Approved 2026-03-20.",
  },
  {
    name: "Immediate Advances",
    tier: 3,
    tier_label: "Tier C – Flexible",
    is_active: true,
    submission_method: "email" as const,
    submission_email: "subs@immediateadvances.com",
    cc_emails: [],
    rep_name: "Laveina Lall",
    rep_email: "laveina@immediateadvances.com",
    min_credit_score: 450,
    min_monthly_revenue: 7000,
    min_time_in_business_months: 4,
    max_amount: 250000,
    factor_rate_range: "1.25 - 1.50+",
    positions_funded: "1st thru 4th",
    repayment_frequency: "Daily",
    funding_speed: "24-48 hrs",
    notes: "ISO DocuSigned 2026-03-03. Fully onboarded 2026-03-25. Docs required: W-9, voided check, DL. Laveina Lall 347-977-9073. Do NOT BCC on submissions.",
  },
  {
    name: "Lexio Capital",
    tier: 3,
    tier_label: "Tier C – Flexible",
    is_active: true,
    submission_method: "email" as const,
    submission_email: "submissions@lexiocapital.com",
    cc_emails: ["yasmany.soler@lexiocapital.com", "verification@lexiocapital.com"],
    rep_name: "Yasmany Soler",
    rep_email: "yasmany.soler@lexiocapital.com",
    min_credit_score: 450,
    min_monthly_revenue: 7000,
    min_time_in_business_months: 4,
    max_amount: 250000,
    factor_rate_range: "1.25 - 1.50+",
    positions_funded: "1st thru 4th",
    repayment_frequency: "Daily",
    funding_speed: "24-48 hrs",
    notes: "C-D paper specialist. ISO Agreement + Questionnaire + VC + DL + W-9 on file. No PSF fees. Contracts to verification@lexiocapital.com. Approved 2026-03-25.",
  },
  {
    name: "NEWITY",
    tier: 1,
    tier_label: "Tier A+ – SBA/Term Loan",
    is_active: true,
    submission_method: "portal" as const,
    portal_url: "https://partner.newitymarket.com/home",
    submission_email: "partners@newitymarket.com",
    cc_emails: [],
    rep_name: "Claudia Savala",
    rep_email: "csavala@newitymarket.com",
    min_credit_score: 640,
    min_time_in_business_months: 24,
    max_amount: 5000000,
    factor_rate_range: "9.5-10.5% APR (SBA); 15-24% fixed (Growth Term)",
    positions_funded: "1st",
    repayment_frequency: "Monthly",
    funding_speed: "Weeks",
    notes: "SBA 7(a) and NEWITY Growth Term Loans. Partner portal access granted 2026-04-08. Referral Agreement signed via PandaDoc. Support: partnersupport@newitymarket.com.",
  },
  {
    name: "ONTAP Capital",
    tier: 2,
    tier_label: "Tier B – Mid-Tier",
    is_active: true,
    submission_method: "email" as const,
    submission_email: "tai@ontapcap.com",
    cc_emails: ["jason@ontapcap.com"],
    rep_name: "Tai; Jason",
    rep_email: "tai@ontapcap.com",
    min_credit_score: 500,
    min_monthly_revenue: 10000,
    min_time_in_business_months: 6,
    max_amount: 500000,
    factor_rate_range: "1.20 - 1.50",
    positions_funded: "1st, 2nd",
    repayment_frequency: "Daily/Weekly",
    funding_speed: "24-48 hrs",
    notes: "ISO Agreement DocuSigned 2026-04-22. Contact Tai (tai@ontapcap.com) or Jason (jason@ontapcap.com) for submissions.",
  },
  {
    name: "Amsterdam Capital Group",
    tier: 2,
    tier_label: "Tier B – Mid-Tier",
    is_active: true,
    submission_method: "email" as const,
    submission_email: "submissions@acgroupinc.com",
    cc_emails: ["mhench@acgroupinc.com"],
    rep_name: "Aleeya Hussain (COO); Brian Corso",
    rep_email: "mhench@acgroupinc.com",
    min_credit_score: 500,
    min_monthly_revenue: 10000,
    min_time_in_business_months: 6,
    max_amount: 500000,
    factor_rate_range: "1.20 - 1.50",
    positions_funded: "1st, 2nd",
    repayment_frequency: "Daily/Weekly",
    funding_speed: "24-48 hrs",
    notes: "ISO Agreement signed via HelloSign 2026-04-22. Docs: 3 months bank stmts + signed app within 30 days (4 months for CA/NY). Offers come from offers@acgroupinc.com. CC mhench@ on submissions.",
  },
  {
    name: "Slim Business Funding",
    tier: 3,
    tier_label: "Tier C – Flexible",
    is_active: true,
    submission_method: "email" as const,
    submission_email: "deals@slimbusinessfunding.com",
    cc_emails: ["joseph@slimbusinessfunding.com"],
    rep_name: "Joseph Maack",
    rep_email: "joseph@slimbusinessfunding.com",
    min_credit_score: 450,
    min_monthly_revenue: 7000,
    min_time_in_business_months: 4,
    max_amount: 1000000,
    factor_rate_range: "1.25 - 1.50+",
    positions_funded: "2nd+ (1st position: restaurants only)",
    repayment_frequency: "Daily/Weekly",
    funding_speed: "24-48 hrs",
    notes: "2nd+ position – all states including TX. Funds reverse positions. Funds previously passed deals that satisfy defaults. 1st position: restaurants only. Up to $1M. Up to 13 pts commission. ISO signed via DocuSign 2026-04-23. Joseph Maack 845-662-9112.",
  },
  {
    name: "Accord Business Funding",
    tier: 3,
    tier_label: "Tier C – Flexible",
    is_active: true,
    submission_method: "email" as const,
    submission_email: "underwriting@accordbf.com",
    cc_emails: ["idelatorre@accordbf.com"],
    rep_name: "Isabella De La Torre",
    rep_email: "idelatorre@accordbf.com",
    min_credit_score: 450,
    min_monthly_revenue: 7000,
    min_time_in_business_months: 4,
    max_amount: 400000,
    factor_rate_range: "1.20 - 1.50+",
    positions_funded: "1st thru 3rd",
    repayment_frequency: "Daily/Weekly",
    funding_speed: "24-48 hrs",
    notes: 'FULLY ONBOARDED 2026-04-29. Subject line: "New Deal. Merchant Name". Docs: completed merchant app + 3 months bank stmts (4 months for CA/NY). Q2 Spiff through June 30: +1pt 1st deal, +2pts 2nd deal, +3pts 3rd deal funded. Isabella De La Torre 404-798-7404. Portal: https://accordbf.com/',
  },
  {
    name: "Elevate Funding",
    tier: 3,
    tier_label: "Tier C – Flexible",
    is_active: true,
    submission_method: "email" as const,
    submission_email: "",
    cc_emails: [],
    min_credit_score: 450,
    min_monthly_revenue: 7000,
    min_time_in_business_months: 4,
    max_amount: 400000,
    factor_rate_range: "1.25 - 1.50+",
    positions_funded: "1st thru 3rd",
    repayment_frequency: "Daily",
    funding_speed: "24-48 hrs",
    notes: "ISO Agreement signed 2026-05-01 via OneSpan e-Sign. Awaiting full onboarding details (submission email, rep contact). Update this record once welcome email arrives.",
  },
];

// Name aliases: seed data used slightly different names for some lenders
const NAME_ALIASES: Record<string, string[]> = {
  "VOX Funding": ["Vox Funding"],
  "NewCo Capital Group": ["Newco Capital Group"],
  "Legend Advance Funding": ["Legend Funding"],
  "Lexio Capital": ["Lexio Financial"],
};

async function main() {
  console.log(`\nUpserting ${CONFIRMED_LENDERS.length} confirmed lenders into Supabase...\n`);
  let updated = 0;
  let inserted = 0;
  let failed = 0;

  for (const lender of CONFIRMED_LENDERS) {
    const namesToTry = [lender.name, ...(NAME_ALIASES[lender.name] ?? [])];
    let existingId: string | null = null;

    for (const candidate of namesToTry) {
      const { data } = await supabaseAdmin
        .from("lenders")
        .select("id")
        .ilike("name", candidate)
        .maybeSingle();
      if (data?.id) { existingId = data.id as string; break; }
    }

    if (existingId) {
      const { error } = await supabaseAdmin
        .from("lenders")
        .update({ ...lender })
        .eq("id", existingId);
      if (error) { console.error(`  ✗ UPDATE ${lender.name}: ${error.message}`); failed++; }
      else { console.log(`  ✓ updated  ${lender.name}`); updated++; }
    } else {
      const { error } = await supabaseAdmin.from("lenders").insert(lender);
      if (error) { console.error(`  ✗ INSERT ${lender.name}: ${error.message}`); failed++; }
      else { console.log(`  ✓ inserted ${lender.name}`); inserted++; }
    }
  }

  console.log(`\nDone: ${updated} updated, ${inserted} inserted, ${failed} failed.`);

  // Show full active list
  const { data: all } = await supabaseAdmin
    .from("lenders")
    .select("name, tier, is_active, submission_email")
    .eq("is_active", true)
    .order("tier")
    .order("name");

  console.log(`\n=== Active lenders in DB (${all?.length ?? 0}) ===`);
  for (const l of all ?? []) {
    console.log(`  [Tier ${l.tier}] ${l.name} — ${l.submission_email || "(portal)"}`);
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
