// Re-run a step, or a run of steps, from Slack.
//
// Matthew, 2026-09-16: "I dont know how to rerun step 13, lets create a command that allows us to do that with
// each step (for testing or any other reason if we want to add a new offer or overwrite the system) ... this way
// if I make a change from now on I can simply update the current step." And: "resend the messages from step 18
// ... up until step 21 ... so we can re run it."
//
//   rerun                      inside a step's thread: that step again, its card updated in the same thread
//   rerun step 13              anywhere in the client's channel: step 13 again, a NEW card at the bottom
//   rerun 18-21 / rerun 18 to 21   the same for each step in order, so the walk can be done again from there
//   start step 13              the same as `rerun step 13`
//
// ‼️ A NEW CARD AT THE BOTTOM, AND THE OLD THREAD SAYS WHERE IT WENT. A step's anchor is its place in the
// channel. Updating it in place would re-run step 18 twenty messages up, where nobody is looking, which is the
// opposite of "resend". So a re-run by number clears the anchor, posts a fresh one at the bottom, and leaves one
// line in the old thread linking to the new card. The old thread and everything typed in it stay.
//
// ‼️ IT RE-RUNS WHAT THE STEP'S RUNNER MAKES AND NOTHING ELSE. Every runner overwrites its own artifact from the
// current record, which is exactly what "I changed the offer, run it again" needs. It does not delete a person's
// decisions: approved keywords stay approved, a picked anchor stays picked, a frozen custom_v1 still refuses. A
// step with no runner (a manual step) just gets its card again.
//
// See docs/STEP-WIRING.md for which code each step runs, generated by scripts/_step-wiring.ts.

import { supabaseAdmin } from "@/lib/db";
import { DELIVERY_STEPS, stepNumber, type StepKey } from "@/config/delivery-steps";

export interface RerunTarget {
  from: number;
  to: number;
}

/**
 * `rerun`, `rerun step 13`, `rerun 18-21`, `rerun steps 18 to 21`, `start step 13`. Pure, for the probe.
 * Returns null when the text is not the command; `{ here: true }` for a bare `rerun` in a thread.
 */
export function parseRerun(text: string): { here: true } | RerunTarget | null {
  const t = text.trim().replace(/^[`*_]+|[`*_]+$/g, "").trim().toLowerCase();
  if (/^(re-?run|restart)( this( step)?)?$/.test(t)) return { here: true };
  const m = /^(?:re-?run|restart|start)\s+(?:steps?\s+)?#?(\d{1,2})(?:\s*(?:-|to|through|until|thru)\s*#?(\d{1,2}))?$/.exec(t);
  if (!m) return null;
  // `start 13` without the word step is too close to a sentence; it needs `step`.
  if (/^start\s+\d/.test(t)) return null;
  const from = Number(m[1]);
  const to = m[2] ? Number(m[2]) : from;
  if (from < 1 || to < from || to > DELIVERY_STEPS.length) return null;
  return { from, to };
}

function keyAt(n: number): StepKey | null {
  return (DELIVERY_STEPS[n - 1]?.key as StepKey | undefined) ?? null;
}

/** Re-run one step. `fresh` posts a new card at the bottom of the channel; otherwise the same thread. */
export async function rerunStep(args: {
  clientId: string;
  stepKey: StepKey;
  fresh: boolean;
  by: string;
}): Promise<{ ok: boolean; line: string }> {
  const n = stepNumber(args.stepKey);
  const step = DELIVERY_STEPS.find((s) => s.key === args.stepKey)!;
  const { data: row } = await supabaseAdmin
    .from("client_delivery_steps")
    .select("status, slack_anchor_ts")
    .eq("client_id", args.clientId)
    .eq("step_key", args.stepKey)
    .maybeSingle();
  if (!row) return { ok: false, line: `${n}. ${step.label}: this client has no row for it.` };

  const oldAnchor = (row.slack_anchor_ts as string | null) ?? null;
  const now = new Date().toISOString();

  // The same fields a reopen clears (delivery-checklist.ts setDeliveryStep), plus the card and, when fresh, the
  // anchor, so the runner and postStep write new ones.
  const patch: Record<string, unknown> = {
    status: "pending",
    completed_at: null,
    completed_by: null,
    skipped_reason: null,
    verified_source: null,
    verified_detail: null,
    verified_at: null,
    error_detail: null,
    slack_message_ts: null,
    updated_at: now,
  };
  if (args.fresh) patch.slack_anchor_ts = null;

  const { error } = await supabaseAdmin
    .from("client_delivery_steps")
    .update(patch)
    .eq("client_id", args.clientId)
    .eq("step_key", args.stepKey);
  if (error) return { ok: false, line: `${n}. ${step.label}: not reset (${error.message}).` };

  const { logClientEvent } = await import("./client-events");
  await logClientEvent({
    clientId: args.clientId,
    stepKey: args.stepKey,
    source: "slack",
    kind: "command",
    author: args.by,
    text: `rerun ${n}${args.fresh ? " (new card)" : ""}`,
    payload: { handler: "step-rerun", before: row.status, fresh: args.fresh },
  });

  const { AUTO_RUNNERS } = await import("./artifacts/registry");
  const { runOneStep, postStep } = await import("./step-engine");
  const { anchorTsFor, markAnchor, refreshStepAnchor } = await import("./step-board");

  // The anchor first, so a fresh card is at the bottom before the runner's notes land in its thread.
  const anchor = await anchorTsFor(args.clientId, args.stepKey);
  await markAnchor(args.clientId, args.stepKey, null).catch(() => {});

  let outcome = "card posted";
  if (AUTO_RUNNERS[args.stepKey]) {
    const res = await runOneStep(args.clientId, args.stepKey);
    outcome = res.ok === false ? `ran and failed: ${res.error ?? "unknown"}` : res.status === "complete" ? "ran and ticked" : "ran, waiting on you";
  } else {
    await postStep(args.clientId, args.stepKey);
  }
  await refreshStepAnchor(args.clientId, args.stepKey).catch(() => {});

  // The old thread says where the step went, so its history reads as a first attempt rather than a dead end.
  if (args.fresh && oldAnchor && anchor && anchor !== oldAnchor) {
    const { channelFor } = await import("./step-board");
    const channel = await channelFor(args.clientId);
    if (channel) {
      const { slack, slackThreadLink } = await import("@/lib/slack-bot");
      await slack
        .postThreadReply(channel, oldAnchor, `:repeat: Re-run by ${args.by}. The new card for this step is here: ${slackThreadLink(channel, anchor)}`)
        .catch(() => {});
    }
  }

  return { ok: true, line: `${n}. ${step.label}: ${outcome}.` };
}

/**
 * Hand a range to the internal route, one step per request.
 *
 * ‼️ NOT A LOOP INSIDE THE SLACK HANDLER. `rerun 18-21` is minutes of work; see the route's header.
 */
export async function startRerunRange(args: { clientId: string; from: number; to: number; by: string }): Promise<{ ok: boolean; error?: string }> {
  const secret = process.env.CRON_SECRET;
  if (!secret) return { ok: false, error: "CRON_SECRET is not set on this environment, so the re-run cannot be dispatched." };
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || "https://mission.srtagency.com";
  try {
    const res = await fetch(`${appUrl}/api/internal/rerun-steps`, {
      method: "POST",
      headers: { authorization: `Bearer ${secret}`, "content-type": "application/json" },
      body: JSON.stringify(args),
      signal: AbortSignal.timeout(15_000),
    });
    return res.status === 202 ? { ok: true } : { ok: false, error: `the route answered ${res.status}` };
  } catch (e) {
    return { ok: false, error: (e as Error).message };
  }
}

/** Re-run steps `from` to `to`, in order, each with a new card at the bottom. Used by the route, one hop at a time. */
export async function rerunRange(args: { clientId: string; from: number; to: number; by: string }): Promise<string[]> {
  const lines: string[] = [];
  for (let n = args.from; n <= args.to; n++) {
    const key = keyAt(n);
    if (!key) continue;
    try {
      const res = await rerunStep({ clientId: args.clientId, stepKey: key, fresh: true, by: args.by });
      lines.push(res.line);
    } catch (e) {
      lines.push(`${n}. ${key}: threw (${(e as Error).message}).`);
    }
  }
  return lines;
}

/** Which client owns a per-client ops channel, for a re-run typed at the top level. Null in a shared channel. */
export async function clientForOpsChannel(channelId: string): Promise<string | null> {
  const { data } = await supabaseAdmin.from("clients").select("id").eq("ops_channel_id", channelId).maybeSingle();
  return (data?.id as string | undefined) ?? null;
}

export function rerunAck(target: RerunTarget | { here: true }, stepKey: string | null): string {
  if ("here" in target) {
    return stepKey
      ? `:repeat: Re-running step ${stepNumber(stepKey as StepKey)} here. Its notes land in this thread and the card updates in place.`
      : ":warning: `rerun` on its own only works inside a step's thread. From the channel, name it: `rerun step 13` or `rerun 18-21`.";
  }
  const span = target.from === target.to ? `step ${target.from}` : `steps ${target.from} to ${target.to}`;
  return `:repeat: Re-running ${span}. Each gets a new card at the bottom of the channel, and its old thread links to it. Decisions already made (approvals, picks, a frozen question set) are kept.`;
}
