// Re-run a step, or a run of steps, from Slack.
//
// Matthew, 2026-09-16: "I dont know how to rerun step 13, lets create a command that allows us to do that with
// each step (for testing or any other reason if we want to add a new offer or overwrite the system) ... this way
// if I make a change from now on I can simply update the current step." And: "resend the messages from step 18
// ... up until step 21 ... so we can re run it."
//
//   rerun                      inside a step's thread: that step again, its card updated in the same thread
//   rerun step 13              anywhere in the client's channel: step 13 again, a NEW card at the bottom
//   rerun 18-21 / rerun 18 to 21   the same for each step in order, so the walk can be done again from there
//   start step 13              the same as `rerun step 13`
//
// ‼️ A NEW CARD AT THE BOTTOM, AND THE OLD THREAD SAYS WHERE IT WENT. A step's anchor is its place in the
// channel. Updating it in place would re-run step 18 twenty messages up, where nobody is looking, which is the
// opposite of "resend". So a re-run by number clears the anchor, posts a fresh one at the bottom, and leaves one
// line in the old thread linking to the new card. The old thread and everything typed in it stay.
//
// ‼️ IT RE-RUNS WHAT THE STEP'S RUNNER MAKES AND NOTHING ELSE. Every runner overwrites its own artifact from the
// current record, which is exactly what "I changed the offer, run it again" needs. It does not delete a person's
// decisions: approved keywords stay approved, a picked anchor stays picked, a frozen custom_v1 still refuses. A
// step with no runner (a manual step) just gets its card again.
//
// ‼️ AND THEN THE BOARD CARRIES ON. A re-run used to reset its step, run it, and stop, so a board mid-onboarding
// sat still until a cron or a button moved it: re-running step 12 on a client whose next unfinished step is 13
// left 13 with no card. continueBoard() runs the same cascade a normal transition runs, bounded by
// reachableCursor, so it posts the next card that is legitimately reachable and never a wall of them.
//
// See docs/STEP-WIRING.md for which code each step runs, generated by scripts/_step-wiring.ts.

import { supabaseAdmin } from "@/lib/db";
import { DELIVERY_STEPS, stepNumber, type StepKey } from "@/config/delivery-steps";

export interface RerunTarget {
  from: number;
  to: number;
}

/**
 * `rerun`, `rerun step 13`, `rerun 18-21`, `rerun steps 18 to 21`, `start step 13`. Pure, for the probe.
 * Returns null when the text is not the command; `{ here: true }` for a bare `rerun` in a thread.
 */
export function parseRerun(text: string): { here: true } | RerunTarget | null {
  const t = text.trim().replace(/^[`*_]+|[`*_]+$/g, "").trim().toLowerCase();
  if (/^(re-?run|restart)( this( step)?)?$/.test(t)) return { here: true };
  const m = /^(?:re-?run|restart|start)\s+(?:steps?\s+)?#?(\d{1,2})(?:\s*(?:-|to|through|until|thru)\s*#?(\d{1,2}))?$/.exec(t);
  if (!m) return null;
  // `start 13` without the word step is too close to a sentence; it needs `step`.
  if (/^start\s+\d/.test(t)) return null;
  const from = Number(m[1]);
  const to = m[2] ? Number(m[2]) : from;
  if (from < 1 || to < from || to > DELIVERY_STEPS.length) return null;
  return { from, to };
}

function keyAt(n: number): StepKey | null {
  return (DELIVERY_STEPS[n - 1]?.key as StepKey | undefined) ?? null;
}

/** Re-run one step. `fresh` posts a new card at the bottom of the channel; otherwise the same thread. */
/**
 * Walk the board forward after a re-run, the way a completed step already does.
 *
 * Matthew, 2026-09-18: "if for example im rerunning step 12 for SRT Agency and I havent completed
 * step all the way up to 17, when I finish with step 12 rerunning, please continue with the
 * onboarding (rerun the step that we are supposed to finish up next)."
 *
 * ‼️ THIS IS THE SAME CASCADE A TRANSITION RUNS, NOT A NEW ONE. /api/internal/board-kick has run
 * these three in this order since 2026-09-11; a re-run simply never called them, so the board sat
 * still until a cron or a button moved it.
 *
 * ‼️ IT CANNOT POST SEVEN CARDS, AND reachableCursor IS WHY. The walk stops at the first step that
 * is not `auto`, so "continue the onboarding" means "post the next card that is legitimately
 * reachable". One anchor at a time is not weakened here; it is the thing being deferred to.
 *
 * ‼️ A RE-RUN THAT LEFT ITS STEP PENDING ADVANCES NOTHING, and that needs no special case: the
 * cursor stops at that step because it is not done. Adding a guard for it would be a second opinion
 * about reachability, and two opinions about reachability is how a board posts a card for work that
 * cannot start.
 *
 * Never throws into the re-run. A board that did not walk is worth a line in the log; it is not
 * worth turning a successful re-run into a failure.
 */
async function continueBoard(clientId: string): Promise<void> {
  try {
    const { ensureReachableAnchors, runReadyAutoSteps, postReadySteps } = await import("./step-engine");
    await ensureReachableAnchors(clientId);
    await runReadyAutoSteps(clientId);
    await postReadySteps(clientId);
    const { refreshDeliveryChecklist } = await import("./delivery-checklist");
    await refreshDeliveryChecklist(clientId).catch(() => {});
  } catch (e) {
    console.error("[clients/step-rerun] the board did not walk on after the re-run:", (e as Error).message);
  }
}

/**
 * Say what the step is still missing, and which earlier step writes it.
 *
 * Matthew, 2026-09-18: "our onboarding brain can read the data it has and if we are missing anything post
 * it directly in the rerun or even suggest to rerun a previous step."
 *
 * ‼️ HERE AND NOT IN postStep's BODY, FOR THREE MEASURED REASONS.
 *   1. A re-run has TWO card paths. A step with a runner goes through runOneStep, which posts a card only
 *      when mode is `auto_then_manual`; a pure `auto` step posts no card at all. A body.push would be
 *      silently absent on every auto step, which is most of the board.
 *   2. postStep's body is EVERY card, not just a re-run's. gap-prompts.ts carries a written decision that
 *      the card gets two door lines and deliberately not the gap list, because five bullets under every
 *      card doubles every card on the board.
 *   3. A bare `rerun` in a thread is the only form whose returned line reaches Slack. `rerun 12` parses as
 *      a RANGE, and that path logs the line to the console, so appending to the return value would be
 *      invisible on the form actually typed.
 *
 * ‼️ IT CAN NEVER FAIL THE RE-RUN. Same rule postStep's own gap block follows: the step has already been
 * reset and run by the time this is reached, so a throw here would report a successful re-run as a failure
 * and leave somebody re-running it again.
 */
async function sayWhatIsMissing(clientId: string, stepKey: StepKey): Promise<void> {
  try {
    const { withLeadScope } = await import("./lead-scope");
    await withLeadScope(async () => {
      const { leadContext } = await import("./lead-context");
      const { gapsFrom } = await import("./step-gaps");
      const { rerunGapBlocks, rerunGapLines, upstreamFills } = await import("./rerun-gaps");
      const { notifyStep } = await import("./step-board");

      const ctx = await leadContext(clientId);
      const g = gapsFrom(ctx, stepKey);
      const ups = upstreamFills(g);
      const text = rerunGapLines(g, ups).join("\n");
      const res = await notifyStep(clientId, stepKey, text, rerunGapBlocks(clientId, g, ups));
      if (!res.ok) console.error(`[clients/step-rerun] the gap block did not post on ${stepKey}:`, res.error);
    });
  } catch (e) {
    console.error(`[clients/step-rerun] could not say what ${stepKey} is missing:`, (e as Error).message);
  }
}

export async function rerunStep(args: {
  clientId: string;
  stepKey: StepKey;
  fresh: boolean;
  by: string;
  /**
   * Walk the board on when this step is done. Default true.
   *
   * ‼️ FALSE FOR EVERY HOP OF A RANGE BUT THE LAST. rerunRange walks 18 to 21 in order; kicking
   * after each one would post step 19's card while 19 is about to be re-run, then post it again.
   */
  advance?: boolean;
}): Promise<{ ok: boolean; line: string }> {
  const n = stepNumber(args.stepKey);
  const step = DELIVERY_STEPS.find((s) => s.key === args.stepKey)!;
  const { data: row } = await supabaseAdmin
    .from("client_delivery_steps")
    .select("status, slack_anchor_ts")
    .eq("client_id", args.clientId)
    .eq("step_key", args.stepKey)
    .maybeSingle();
  if (!row) return { ok: false, line: `${n}. ${step.label}: this client has no row for it.` };

  const oldAnchor = (row.slack_anchor_ts as string | null) ?? null;
  const now = new Date().toISOString();

  // The same fields a reopen clears (delivery-checklist.ts setDeliveryStep), plus the card and, when fresh, the
  // anchor, so the runner and postStep write new ones.
  const patch: Record<string, unknown> = {
    status: "pending",
    completed_at: null,
    completed_by: null,
    skipped_reason: null,
    verified_source: null,
    verified_detail: null,
    verified_at: null,
    error_detail: null,
    slack_message_ts: null,
    updated_at: now,
  };
  if (args.fresh) patch.slack_anchor_ts = null;

  const { error } = await supabaseAdmin
    .from("client_delivery_steps")
    .update(patch)
    .eq("client_id", args.clientId)
    .eq("step_key", args.stepKey);
  if (error) return { ok: false, line: `${n}. ${step.label}: not reset (${error.message}).` };

  const { logClientEvent } = await import("./client-events");
  await logClientEvent({
    clientId: args.clientId,
    stepKey: args.stepKey,
    source: "slack",
    kind: "command",
    author: args.by,
    text: `rerun ${n}${args.fresh ? " (new card)" : ""}`,
    payload: { handler: "step-rerun", before: row.status, fresh: args.fresh },
  });

  const { AUTO_RUNNERS } = await import("./artifacts/registry");
  const { runOneStep, postStep } = await import("./step-engine");
  const { anchorTsFor, markAnchor, refreshStepAnchor } = await import("./step-board");

  // The anchor first, so a fresh card is at the bottom before the runner's notes land in its thread.
  const anchor = await anchorTsFor(args.clientId, args.stepKey);
  await markAnchor(args.clientId, args.stepKey, null).catch(() => {});

  let outcome = "card posted";
  if (AUTO_RUNNERS[args.stepKey]) {
    const res = await runOneStep(args.clientId, args.stepKey);
    outcome = res.ok === false ? `ran and failed: ${res.error ?? "unknown"}` : res.status === "complete" ? "ran and ticked" : "ran, waiting on you";
  } else {
    await postStep(args.clientId, args.stepKey);
  }
  await refreshStepAnchor(args.clientId, args.stepKey).catch(() => {});

  // The old thread says where the step went, so its history reads as a first attempt rather than a dead end.
  if (args.fresh && oldAnchor && anchor && anchor !== oldAnchor) {
    const { channelFor } = await import("./step-board");
    const channel = await channelFor(args.clientId);
    if (channel) {
      const { slack, slackThreadLink } = await import("@/lib/slack-bot");
      await slack
        .postThreadReply(channel, oldAnchor, `:repeat: Re-run by ${args.by}. The new card for this step is here: ${slackThreadLink(channel, anchor)}`)
        .catch(() => {});
    }
  }

  await sayWhatIsMissing(args.clientId, args.stepKey);

  if (args.advance !== false) await continueBoard(args.clientId);

  return { ok: true, line: `${n}. ${step.label}: ${outcome}.` };
}

/**
 * Hand a range to the internal route, one step per request.
 *
 * ‼️ NOT A LOOP INSIDE THE SLACK HANDLER. `rerun 18-21` is minutes of work; see the route's header.
 */
export async function startRerunRange(args: { clientId: string; from: number; to: number; by: string }): Promise<{ ok: boolean; error?: string }> {
  const secret = process.env.CRON_SECRET;
  if (!secret) return { ok: false, error: "CRON_SECRET is not set on this environment, so the re-run cannot be dispatched." };
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || "https://mission.srtagency.com";
  try {
    const res = await fetch(`${appUrl}/api/internal/rerun-steps`, {
      method: "POST",
      headers: { authorization: `Bearer ${secret}`, "content-type": "application/json" },
      body: JSON.stringify(args),
      signal: AbortSignal.timeout(15_000),
    });
    return res.status === 202 ? { ok: true } : { ok: false, error: `the route answered ${res.status}` };
  } catch (e) {
    return { ok: false, error: (e as Error).message };
  }
}

/** Re-run steps `from` to `to`, in order, each with a new card at the bottom. Used by the route, one hop at a time. */
export async function rerunRange(args: { clientId: string; from: number; to: number; by: string }): Promise<string[]> {
  const lines: string[] = [];
  for (let n = args.from; n <= args.to; n++) {
    const key = keyAt(n);
    if (!key) continue;
    try {
      // ‼️ ONLY THE LAST HOP WALKS THE BOARD ON. Kicking after each step would post the card for a
      // step this loop is about to re-run, and then post it again.
      const res = await rerunStep({ clientId: args.clientId, stepKey: key, fresh: true, by: args.by, advance: false });
      lines.push(res.line);
    } catch (e) {
      lines.push(`${n}. ${key}: threw (${(e as Error).message}).`);
    }
  }
  await continueBoard(args.clientId);
  return lines;
}

/** Which client owns a per-client ops channel, for a re-run typed at the top level. Null in a shared channel. */
export async function clientForOpsChannel(channelId: string): Promise<string | null> {
  const { data } = await supabaseAdmin.from("clients").select("id").eq("ops_channel_id", channelId).maybeSingle();
  return (data?.id as string | undefined) ?? null;
}

export function rerunAck(target: RerunTarget | { here: true }, stepKey: string | null): string {
  if ("here" in target) {
    return stepKey
      ? `:repeat: Re-running step ${stepNumber(stepKey as StepKey)} here. Its notes land in this thread and the card updates in place. When it is done the board carries on to whatever is next.`
      : ":warning: `rerun` on its own only works inside a step's thread. From the channel, name it: `rerun step 13` or `rerun 18-21`.";
  }
  const span = target.from === target.to ? `step ${target.from}` : `steps ${target.from} to ${target.to}`;
  return `:repeat: Re-running ${span}. Each gets a new card at the bottom of the channel, and its old thread links to it. Decisions already made (approvals, picks, a frozen question set) are kept. When the last one is done the board carries on to whatever is next.`;
}
