-- The multi-tenant client hub: which hostnames this project serves, and what they serve.
-- Safe to run more than once.

create extension if not exists pgcrypto;

-- ─────────────────────────────────────────────────────────────────────────────
-- client_hosts — the hostnames, and the Vercel attachment ledger
-- ─────────────────────────────────────────────────────────────────────────────
--
-- WHY A TABLE, rather than deriving learn.{domain} from clients.domain plus
-- subdomain_convention. Derivation would make a LIVE, INDEXED client website depend on a
-- string in clients.domain staying correct, and on subdomainLabel()'s defensive trailing
-- domain stripping continuing to strip the right thing. Somebody correcting a typo on the
-- client board would then 404 a page Google has already crawled.
--
-- A row here exists because POST /v10/projects/{id}/domains returned 200. It records what
-- was ATTACHED, not what was intended: the same split as `verified` versus `added` in
-- client_dns_records, applied one layer up.
create table if not exists public.client_hosts (
  id          uuid        primary key default gen_random_uuid(),
  client_id   uuid        not null references public.clients(id) on delete cascade,

  -- The FULL hostname, lowercase, no port, no trailing dot. The OPPOSITE of
  -- client_dns_records.host, which is the LABEL only because a label is what a registrar's
  -- Host box wants. This is what arrives in the Host header, so it is stored as it arrives.
  host        text        not null,
  kind        text        not null,

  -- An off switch that does not touch clients. A churned client's hub stops serving
  -- without deleting the row that records we once attached it.
  enabled     boolean     not null default true,

  -- What Vercel said, kept as CONTEXT and never as status. client_dns_records owns the
  -- status vocabulary and there must not be a second one: `misconfigured` before the CNAME
  -- propagates is the same fact checkRecord() already reports as not_found.
  vercel_attached_at   timestamptz,
  vercel_verified      boolean,
  vercel_misconfigured boolean,
  vercel_checked_at    timestamptz,
  vercel_error         text,

  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table public.client_hosts drop constraint if exists client_hosts_kind_check;
alter table public.client_hosts add constraint client_hosts_kind_check
  check (kind in ('hub', 'reviews'));

-- THE hot-path index, and a correctness constraint. One hostname belongs to exactly one
-- client: two clients claiming one host is not an ambiguity to resolve at read time, it is
-- a write that must fail.
create unique index if not exists client_hosts_host_key on public.client_hosts (lower(host));
create index if not exists client_hosts_client_idx on public.client_hosts (client_id);
create unique index if not exists client_hosts_client_kind_key
  on public.client_hosts (client_id, kind);

alter table public.client_hosts enable row level security;

-- ─────────────────────────────────────────────────────────────────────────────
-- client_pages — what the hub publishes
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.client_pages (
  id           uuid        primary key default gen_random_uuid(),
  client_id    uuid        not null references public.clients(id) on delete cascade,
  slug         text        not null,
  title        text        not null,

  -- The audit question this page answers, stored VERBATIM rather than referenced.
  -- audit_reports.prompts is regenerated by every run, so a reference would let the next
  -- audit silently turn a published page into the answer to a question nobody asked.
  question     text        not null,
  prompt_block text,

  answer_md        text not null,
  meta_description text,

  status       text        not null default 'draft',
  published_at timestamptz,

  -- Provenance, so a page traces back to the run that asked the question.
  source_report_id uuid,

  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

alter table public.client_pages drop constraint if exists client_pages_status_check;
alter table public.client_pages add constraint client_pages_status_check
  check (status in ('draft', 'published', 'archived'));

alter table public.client_pages drop constraint if exists client_pages_block_check;
alter table public.client_pages add constraint client_pages_block_check
  check (prompt_block is null or prompt_block in ('SERVICIO', 'COMPARATIVO', 'INFO', 'MARCA'));

-- Per client, not global: two clinics may both want /botox-vs-dysport, and they are on
-- different hostnames.
create unique index if not exists client_pages_client_slug_key
  on public.client_pages (client_id, lower(slug));

-- Exactly what the hub index and the sitemap read.
create index if not exists client_pages_published_idx
  on public.client_pages (client_id, published_at desc) where status = 'published';

alter table public.client_pages enable row level security;

-- ─────────────────────────────────────────────────────────────────────────────
-- review_tool_submissions — SRT-Review-Tool-BUILD-SPEC-v2.md
-- ─────────────────────────────────────────────────────────────────────────────
--
-- NO NAME, EMAIL, PHONE, IP, USER AGENT, SESSION ID OR DEVICE FINGERPRINT. If a field
-- could identify her it is not collected, and THE ABSENCE OF THE COLUMN IS THE
-- ENFORCEMENT: a route cannot store what there is nowhere to put. Adding one of these
-- columns later is a spec violation, not a feature.
--
-- It also forecloses IP rate limiting, deliberately. Any limit here is a per-client daily
-- count read back from this table, never a bucket keyed on something identifying.
create table if not exists public.review_tool_submissions (
  id                   uuid        primary key default gen_random_uuid(),
  client_id            uuid        not null references public.clients(id) on delete cascade,
  question_set_version text        not null,
  answers              jsonb       not null,
  posted_destination   text,
  created_at           timestamptz not null default now()
);

create index if not exists review_tool_submissions_client_idx
  on public.review_tool_submissions (client_id, created_at desc);

alter table public.review_tool_submissions enable row level security;
