-- Intel brief cache + the Loom transcript gate. ADD ONLY, safe to re-run.
-- Run AFTER 2026-08-03-niche-briefs.sql, which creates the niche_briefs table.

-- The rest of the intel brief (pains, horror stories, channels, night questions, the $100 bills,
-- objections) lands on the same row as the avatars because it caches on the same key and the
-- same clock. Block F (3 worst / 3 best / the pick) stays in `avatars`.
--
-- { "pains":[{"says","whyItHurts"}], "horrorStories":[{"story","voice","source","hook","installs"}],
--   "channels":[{"channel","whatTheyHate"}], "nightQuestions":[text],
--   "hundredDollarBills":[{"what","why"}], "objections":[{"fear","disarm"}] }
--
-- `horrorStories[].voice` is verbatim and `source` is the URL it was read at. A quote without a
-- link does not ship, because a quote we cannot point at is a quote we invented.
alter table niche_briefs add column if not exists brief            jsonb;

-- Separate from created_at: the avatars and the brief are generated by different commands and
-- expire independently, so one timestamp for both would silently serve a stale half.
alter table niche_briefs add column if not exists brief_created_at timestamptz;

-- The Loom transcript, pasted into the prospect's thread after recording.
--
-- This is the delivery-email gate (SRT_Loom_Playbook.md). The agent REFUSES to draft the
-- hand-over email until this exists, because that email quotes two timestamps and the strongest
-- moment of the video. Without the transcript both would be invented, and a prospect who clicks
-- 3:15 and finds something else there stops believing everything around it.
alter table audit_reports add column if not exists loom_transcript text;
