// The closing questions — filed against delivery step 20, generated when step 18 completes.
//
// Matthew: "for step 20 ideally hand me a PDF with the questions we should be asking for this
// client based on the reports we did ... considering our closer framework we want to focus on
// clarify why they are here, label them with a problem, overview they're previous pain, sell
// them on the dream outcome, explain away they're concerns, and THEN, we reinforce they're
// decision by starting to show everything we did and after we collect payment asking questions
// about the funnel, online presence, GBP profile, capture DNS and all the rest, we cant capture
// all of this if they are not willing to put a card on file. Give me a list of 33 questions you
// would ask based on the report we did and I will select the ones I like."
//
// The call sheet is the sixty minutes. This is the CONVERSATION inside it: step 20 used to hand
// over a NAP read-aloud and a capture page and nothing to actually run the call with.
//
// ‼️ THE FACTS ARE CODE. THE QUESTIONS ARE THE MODEL'S. IT INVENTS NO NUMBER.
//
// Same split buildCoachNotes() makes in call-script.ts, and for the same reason stated there: a
// hallucinated figure in a document read aloud on a sales call is not one bad line, it is the
// whole call. buildQuestionFacts() assembles the score, the questions this business is absent
// from, who was named instead, the presence sweep, the review gaps and the site intelligence BY
// HAND, and they are handed over as "the only numbers that exist".
//
// ‼️ THIS IS THE FIRST ARTIFACT IN THIS FOLDER WITH A MODEL CALL IN IT, and that is not a
// precedent for the others. custom-question-set.ts states its own case at length: the tracked
// set has to be deterministic or the day-30 comparison compares two different measurements. This
// document is neither tracked nor measured — it is read once, by one person, on one call — so a
// model choosing the wording costs nothing that a re-run would break.
//
// ‼️ absent organic prompts COME FROM audit_runs.prompt, NEVER audit_reports.prompts.
// findings.ts states the hazard: that column is REGENERATED by every audit run, so quoting it
// would let a later scan rewrite the questions in a document already read out to a client.
//
// ‼️ IT DOES NOT CALL deliverArtifact, AND THAT IS DELIBERATE.
// deliverArtifact -> anchorTsFor -> postStepAnchor CREATES the step's Slack anchor. This runs
// when step 18 completes, so posting the file would put step 20's top-level message in the
// channel while step 18 is still the cursor — exactly the leak reachableCursor's doc block in
// step-engine.ts names, and the reason one-anchor-at-a-time exists. It stores the bytes and
// writes call_held.output_ref; step 20's own card links it the moment that step legitimately
// appears, through the outputRefsFor / docLink path every other card already uses.

import { supabaseAdmin } from "@/lib/db";
import { callClaudeJSON } from "@/lib/claude-calls";
import { spokenPromises } from "@/lib/audit-engine/delivery-guards";
import { noDashes } from "@/lib/audit-engine/email-assistant";
import { buildAliases, isMentioned } from "@/lib/audit-engine/mention-match";
import { loadSweep, effectiveStatus, countByStatus } from "../presence-sweep";
import { loadReviewAudit, isRecorded } from "../review-audit";
import { selectedCompetitors, tallyRecommended } from "../competitors";
import { platformByKey } from "@/config/presence-platforms";
import { clickPathFor, loadDnsRows } from "../dns-records";
import { storeGeneratedDoc } from "../onboarding-docs";
import type { SiteIntel } from "../site-intel";
import {
  startDoc,
  finishDoc,
  newPage,
  ensureSpace,
  coverHeading,
  sectionHeading,
  paragraph,
  plainFooter,
  setColor,
  MARGIN,
  PAGE_W,
  CONTENT_W,
  MUTED,
  AMBER,
  REEF,
  RED,
  CARD_BORDER,
  type PageState,
} from "@/lib/pdf/kit";
import type { AutoResult } from "./registry";

// ─────────────────────────────────────────────────────────────────────────────
// CLOSER — already this repo's spine
// ─────────────────────────────────────────────────────────────────────────────

/**
 * ‼️ THE ORDER IS THE ARGUMENT AND IT IS NOT ALPHABETICAL BY ACCIDENT.
 *
 * call-coach/suggest/route.ts's STATIC_RULES: "CLOSER is the spine and it runs in order". The
 * same six stages drive the live coach on the phone, so a closing document ordered any other way
 * would have Matthew reading section 4 while the extension is coaching him through section 2.
 *
 * `want` is a target, not a quota. The validator holds the TOTAL at 33 and requires every
 * section to be non-empty; forcing an exact per-section count would make the model pad a
 * section the report gave it nothing for, and a padded question is one that gets asked.
 */
export const CLOSER_SECTIONS = [
  {
    key: "clarify",
    letter: "C",
    title: "Clarify",
    want: 6,
    purpose: "why they are on this call at all",
  },
  {
    key: "label",
    letter: "L",
    title: "Label",
    want: 5,
    purpose: "name the problem in their words, not ours",
  },
  {
    key: "overview",
    letter: "O",
    title: "Overview",
    want: 6,
    purpose: "their previous pain: what they already tried, and what it cost",
  },
  {
    key: "sell",
    letter: "S",
    title: "Sell",
    want: 5,
    purpose: "the dream outcome, in their own terms",
  },
  {
    key: "explain",
    letter: "E",
    title: "Explain",
    want: 6,
    purpose: "their concerns, answered before they have to raise them",
  },
  {
    key: "reinforce",
    letter: "R",
    title: "Reinforce",
    want: 5,
    purpose: "show what we already did, then ask for the card",
  },
] as const;

export type CloserKey = (typeof CLOSER_SECTIONS)[number]["key"];

/** Matthew asked for 33 and picks the ones he likes. It is the contract, not a target. */
export const TOTAL_QUESTIONS = 33;

/** One breath, read off a screen while somebody is on the phone. Same cap `call` enforces. */
export const MAX_QUESTION_WORDS = 25;

// ─────────────────────────────────────────────────────────────────────────────
// The facts, assembled by hand
// ─────────────────────────────────────────────────────────────────────────────

export interface QuestionFacts {
  clientName: string;
  city: string;
  vertical: string;
  /** audit_reports.score, or null when no baseline exists. Never computed here. */
  score: number | null;
  enginesRun: string[];
  /** Organic questions the business did not come back in. The money gap. */
  absentPrompts: string[];
  /** Organic questions it DID come back in. Named so nothing claims a total absence. */
  presentPrompts: string[];
  /** Prompts that were never measured. Not counted as an absence. */
  unmeasured: number;
  namedInstead: Array<{ name: string; timesNamed: number }>;
  confirmedCompetitors: string[];
  presence: {
    coreMismatch: string[];
    coreMissing: string[];
    coreNotChecked: string[];
    coreMatch: number;
    coreTotal: number;
  };
  reviews: {
    clientRecorded: Array<{ platform: string; count: number }>;
    competitorRecorded: Array<{ subject: string; platform: string; count: number }>;
    outstanding: number;
    total: number;
  };
  technical: {
    registrar: string | null;
    dnsProvider: string | null;
    cms: string | null;
    mailProvider: string | null;
    resolverHealthy: boolean;
    robotsBlocks: string[];
    siteSignals: string[];
  };
}

/**
 * Everything true about this client that a closing question may be built on.
 *
 * ‼️ ZERO MODEL CALLS AND ZERO DERIVED CLAIMS. Every field here is either a column or a count of
 * rows. `absentPrompts` is the only one that needed a decision, and it is the same one
 * findings.ts already makes: a prompt is absent when no engine named the business, and a prompt
 * that was never measured is neither absent nor present.
 */
export async function buildQuestionFacts(clientId: string): Promise<QuestionFacts | null> {
  const { data: client } = await supabaseAdmin
    .from("clients")
    .select(
      "legal_name, dba_name, website, domain, city, state, vertical_slug, business_type, site_intel"
    )
    .eq("id", clientId)
    .maybeSingle();

  if (!client) return null;

  const clientName = ((client.dba_name || client.legal_name) as string) ?? "";
  const aliases = buildAliases(clientName, (client.website as string | null) ?? (client.domain as string | null));

  const { data: report } = await supabaseAdmin
    .from("audit_reports")
    .select("id, score, engines, robots_check, site_signals")
    .eq("client_id", clientId)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  // ‼️ audit_runs.prompt, NOT audit_reports.prompts. See the file header.
  const { data: runRows } = report
    ? await supabaseAdmin
        .from("audit_runs")
        .select("prompt, engine, mentioned, recommended")
        .eq("report_id", report.id)
    : { data: null };

  const runs = (runRows ?? []).map((r) => ({
    prompt: r.prompt as string,
    engine: r.engine as string,
    mentioned: (r.mentioned as boolean | null) ?? null,
    recommended: (r.recommended as string[] | null) ?? [],
  }));

  // Collapse the engines: named when at least one engine named them, unmeasured only when no
  // engine produced an answer at all. The same rollup findings.ts prints on the page.
  const byPrompt = new Map<string, boolean | null>();
  for (const r of runs) {
    const current = byPrompt.get(r.prompt);
    if (r.mentioned === true) byPrompt.set(r.prompt, true);
    else if (current === undefined) byPrompt.set(r.prompt, r.mentioned);
  }

  const absentPrompts: string[] = [];
  const presentPrompts: string[] = [];
  let unmeasured = 0;
  for (const [prompt, mentioned] of byPrompt) {
    // A prompt that already names the business proves almost nothing, so it is not part of the
    // gap. Same 90/10 reasoning report-view.ts weights on.
    if (isMentioned(prompt, aliases)) continue;
    if (mentioned === null) unmeasured += 1;
    else if (mentioned) presentPrompts.push(prompt);
    else absentPrompts.push(prompt);
  }

  const sweep = await loadSweep(clientId);
  const core = sweep.filter((r) => r.tier === "core_six");
  const label = (key: string) => platformByKey(key)?.label ?? key;

  const reviewRows = await loadReviewAudit(clientId);
  const recorded = reviewRows.filter(isRecorded);

  const competitors = await selectedCompetitors(clientId);
  const intel = (client.site_intel as SiteIntel | null) ?? null;

  const robots =
    (report?.robots_check as Array<{ engine: string; role: string }> | null) ?? null;

  return {
    clientName,
    city: [client.city, client.state].filter(Boolean).join(", "),
    vertical: ((client.vertical_slug as string | null) || (client.business_type as string | null)) ?? "",
    score: (report?.score as number | null) ?? null,
    enginesRun: (report?.engines as string[] | null) ?? [],
    absentPrompts,
    presentPrompts,
    unmeasured,
    namedInstead: tallyRecommended(runs, aliases)
      .slice(0, 8)
      .map((t) => ({ name: t.name, timesNamed: t.timesNamed })),
    confirmedCompetitors: competitors.map((c) => c.name),
    presence: {
      coreMismatch: core.filter((r) => effectiveStatus(r) === "mismatch").map((r) => label(r.platform)),
      coreMissing: core.filter((r) => effectiveStatus(r) === "missing").map((r) => label(r.platform)),
      coreNotChecked: core.filter((r) => effectiveStatus(r) === "not_checked").map((r) => label(r.platform)),
      coreMatch: countByStatus(core).match,
      coreTotal: core.length,
    },
    reviews: {
      clientRecorded: recorded
        .filter((r) => r.subjectType === "client")
        .map((r) => ({ platform: r.platform, count: r.reviewCount ?? 0 })),
      competitorRecorded: recorded
        .filter((r) => r.subjectType === "competitor")
        .map((r) => ({ subject: r.subjectName, platform: r.platform, count: r.reviewCount ?? 0 })),
      outstanding: reviewRows.length - recorded.length,
      total: reviewRows.length,
    },
    technical: {
      registrar: intel?.registration.registrar ?? null,
      dnsProvider: intel?.dnsProvider ?? null,
      cms: intel?.cms ?? null,
      mailProvider: intel?.mailProvider ?? null,
      resolverHealthy: intel?.resolverHealthy ?? false,
      robotsBlocks: (robots ?? []).filter((r) => r.role === "search").map((r) => r.engine),
      siteSignals: ((report?.site_signals as Array<{ detail: string }> | null) ?? []).map((s) => s.detail),
    },
  };
}

/**
 * The facts, rendered for the prompt.
 *
 * ‼️ FRAMED AS "THE ONLY NUMBERS THAT EXIST", the same words the Call Coach's brief uses. Without
 * that framing a model rounds 10/100 into "under 15%" and supplies a competitor nobody measured.
 * An ABSENCE is stated out loud rather than left silent: absent beats forbidden, the rule this
 * repo applies to the price gate and to miniCheckContext.
 */
export function factsBlock(f: QuestionFacts): string {
  const lines: string[] = [];
  const say = (label: string, value: string) => lines.push(`${label}: ${value}`);

  say("BUSINESS", `${f.clientName}${f.city ? ` in ${f.city}` : ""}`);
  say("WHAT THEY ARE", f.vertical || "not recorded, so do not name a category");

  if (f.score === null) {
    say("SCORE", "NONE. No baseline exists. Do not cite a score, a percentage or a fraction.");
  } else {
    say("SCORE", `${f.score} out of 100, measured across ${f.enginesRun.length || 1} engine(s)`);
  }

  if (f.absentPrompts.length) {
    lines.push(
      `QUESTIONS THEY DID NOT COME BACK IN (${f.absentPrompts.length}), verbatim as run:`,
      ...f.absentPrompts.slice(0, 20).map((p) => `  - ${p}`)
    );
  } else {
    say("QUESTIONS THEY DID NOT COME BACK IN", "NONE recorded. Do not claim an absence.");
  }

  if (f.presentPrompts.length) {
    lines.push(
      `QUESTIONS THEY DID COME BACK IN (${f.presentPrompts.length}). Never say they are invisible:`,
      ...f.presentPrompts.slice(0, 8).map((p) => `  - ${p}`)
    );
  }
  if (f.unmeasured) {
    say("NEVER MEASURED", `${f.unmeasured} question(s). These are not absences and may not be counted as any.`);
  }

  if (f.namedInstead.length) {
    lines.push(
      "NAMED INSTEAD OF THEM, with the count each one actually earned:",
      ...f.namedInstead.map((c) => `  - ${c.name}, named in ${c.timesNamed}`)
    );
  } else {
    say("NAMED INSTEAD", "NONE. No competing business was named often enough to record.");
  }

  if (f.confirmedCompetitors.length) {
    say("COMPETITORS THEY CONFIRMED ON THE BOARD", f.confirmedCompetitors.join(", "));
  }

  const p = f.presence;
  say(
    "PRESENCE, CORE SIX",
    `${p.coreMatch} of ${p.coreTotal} match the canonical record` +
      (p.coreMismatch.length ? `; disagree: ${p.coreMismatch.join(", ")}` : "") +
      (p.coreMissing.length ? `; no listing: ${p.coreMissing.join(", ")}` : "") +
      (p.coreNotChecked.length
        ? `; NOT CHECKED (this is not a finding that they are correct): ${p.coreNotChecked.join(", ")}`
        : "")
  );

  const r = f.reviews;
  if (r.total === 0) {
    say("REVIEWS", "The review audit has not been seeded. No review number exists.");
  } else if (!r.clientRecorded.length && !r.competitorRecorded.length) {
    say("REVIEWS", `${r.total} rows, NONE read yet. Nobody has counted a review. Do not imply zero.`);
  } else {
    lines.push("REVIEWS, only what somebody actually counted:");
    for (const x of r.clientRecorded) lines.push(`  - them, ${x.platform}: ${x.count}`);
    for (const x of r.competitorRecorded) lines.push(`  - ${x.subject}, ${x.platform}: ${x.count}`);
    if (r.outstanding) lines.push(`  - ${r.outstanding} of ${r.total} rows are still unread and prove nothing`);
  }

  const t = f.technical;
  const tech = [
    t.registrar ? `domain registered with ${t.registrar}` : null,
    t.dnsProvider ? `DNS managed at ${t.dnsProvider}` : null,
    t.cms ? `site built on ${t.cms}` : null,
    t.mailProvider ? `email on ${t.mailProvider}` : null,
    t.robotsBlocks.length ? `robots.txt blocks ${t.robotsBlocks.join(", ")} by name` : null,
    ...t.siteSignals,
  ].filter(Boolean);
  say("TECHNICAL", tech.length ? tech.join("; ") : "nothing was measured about the site or its DNS");
  if (!t.resolverHealthy) {
    say("TECHNICAL CAVEAT", "the DNS lookup did not complete, so nothing about DNS may be asserted");
  }

  return lines.join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// The generation
// ─────────────────────────────────────────────────────────────────────────────

export interface DraftedQuestion {
  section: CloserKey;
  question: string;
}

interface Drafted {
  questions: DraftedQuestion[];
}

const SECTION_KEYS = new Set<string>(CLOSER_SECTIONS.map((s) => s.key));

function wordCount(s: string): number {
  return s.trim().split(/\s+/).filter(Boolean).length;
}

/**
 * Every rule the questions have to satisfy, as data, so validate() and describeInvalid() cannot
 * disagree about what failed.
 *
 * ‼️ describeInvalid MUST COVER THE WHOLE VALIDATOR, AND booking-script.ts RECORDS WHAT HAPPENS
 * WHEN IT DOES NOT: it described only the shape, so when the word cap was what failed the
 * correction retry got a rejection with no reason and answered "I cannot fix the error without
 * knowing what the rejection reason was" — which is not JSON, so the parse threw, on every run.
 * Every branch below quotes the offending line back.
 */
export function questionProblems(parsed: unknown): string[] {
  const problems: string[] = [];
  const d = parsed as Drafted | null;

  if (!d || typeof d !== "object" || !Array.isArray(d.questions)) {
    return ['the payload has no "questions" array at the top level'];
  }

  const bad = d.questions.filter(
    (q) => !q || typeof q.question !== "string" || !q.question.trim() || !SECTION_KEYS.has(q.section)
  );
  if (bad.length) {
    problems.push(
      `${bad.length} entr(y|ies) are not { section, question } with section one of ` +
        `${[...SECTION_KEYS].join(" | ")}: ${JSON.stringify(bad.slice(0, 3))}`
    );
    // Nothing below can be trusted about a malformed entry, so stop here rather than piling on.
    return problems;
  }

  if (d.questions.length !== TOTAL_QUESTIONS) {
    problems.push(
      `there are ${d.questions.length} questions and there must be exactly ${TOTAL_QUESTIONS}`
    );
  }

  const empty = CLOSER_SECTIONS.filter((s) => !d.questions.some((q) => q.section === s.key));
  if (empty.length) {
    problems.push(`these sections have no questions at all: ${empty.map((s) => s.key).join(", ")}`);
  }

  const long = d.questions.filter((q) => wordCount(q.question) > MAX_QUESTION_WORDS);
  if (long.length) {
    problems.push(
      `${long.length} question(s) run past ${MAX_QUESTION_WORDS} words and are read aloud on a ` +
        `phone, so they have to be shortened: ` +
        long
          .slice(0, 5)
          .map((q) => `[${wordCount(q.question)} words] "${q.question}"`)
          .join(" | ")
    );
  }

  // ‼️ A PRICE, A GUARANTEE OR A PROMISE OF CUSTOMERS FAILS THE GENERATION, not a warning above
  // it. These questions are read out loud to a client who is about to put a card on file, and
  // spokenPromises() is the same guard the delivery email and every phone script run through.
  for (const q of d.questions) {
    const hits = spokenPromises(q.question);
    if (hits.length) {
      problems.push(
        `"${q.question}" ${hits.map((h) => h.detail).join(" and ")}. This document may not ` +
          `promise customers, revenue, a return or a guarantee, and may not quote a price.`
      );
    }
  }

  return problems;
}

const SYSTEM = `You write the questions a consultant asks on a closing call.

You are given the ONLY facts that exist about this business. They were measured. Everything else
is unknown to you, and a number you did not receive is a number you may not write.

RULES, all of them absolute:
- Ask questions. Every entry ends in a question mark. Never a statement, never a script line.
- ${MAX_QUESTION_WORDS} words maximum per question. It is read aloud off a screen mid-call.
- Never quote a price, a fee, a discount or a package.
- Never promise customers, leads, revenue, growth, a return or a guarantee. Not even a hedged one.
- Never invent a figure, a competitor, a platform or a finding. If a fact is not in the block
  below, it does not exist. An absence stated in the block ("NONE", "NOT CHECKED") is a fact you
  may use, and it is never evidence of the opposite.
- No em dashes anywhere.
- The questions are for the OWNER to answer. Do not write questions we answer for ourselves.

The order is the CLOSER framework and it is the argument of the call:`;

function userPrompt(f: QuestionFacts): string {
  const sections = CLOSER_SECTIONS.map(
    (s) => `  ${s.key} (${s.letter} ${s.title}) - ${s.purpose}. Aim for about ${s.want}.`
  ).join("\n");

  return [
    `SECTIONS:\n${sections}`,
    "",
    `Write exactly ${TOTAL_QUESTIONS} questions in total, spread across all six sections. The`,
    "per-section numbers above are a target, not a quota: put a question where it belongs rather",
    "than padding a section, but every section must have at least one.",
    "",
    "Ground the specific ones in the facts. A question naming a real absent question of theirs,",
    "a real business named instead of them, or a real listing that disagrees is worth ten generic",
    "ones. Reinforce is where we show what has already been done and ask for the card.",
    "",
    "THE ONLY FACTS THAT EXIST:",
    factsBlock(f),
  ].join("\n");
}

/**
 * Draft the 33.
 *
 * ‼️ maxTokens STAYS UNDER 8000. claude-calls.ts retries a truncated response once at double the
 * budget, but only `if (requestedTokens < MAX_RETRY_TOKENS)` — passing the cap itself silently
 * disables the only recovery for truncation, and the cut-off response then fails as an
 * unparseable-JSON error whose message says nothing about length.
 */
export async function draftClosingQuestions(f: QuestionFacts): Promise<DraftedQuestion[]> {
  const result = await callClaudeJSON<Drafted>({
    model: "claude-sonnet-4-6",
    maxTokens: 4000,
    temperature: 0.4,
    system: SYSTEM,
    user: userPrompt(f),
    schemaHint: `{ "questions": [ { "section": "clarify|label|overview|sell|explain|reinforce", "question": string } ] }  // exactly ${TOTAL_QUESTIONS} entries`,
    validate: (parsed): parsed is Drafted => questionProblems(parsed).length === 0,
    describeInvalid: (parsed) => questionProblems(parsed).join(" ALSO: "),
  });

  // noDashes is the guarantee; the prompt line above it is only the request. Same belt the whole
  // outreach stack wears, and live runs confirm the model emits them anyway.
  return result.data.questions.map((q) => ({ section: q.section, question: noDashes(q.question) }));
}

// ─────────────────────────────────────────────────────────────────────────────
// The document
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A ruled checkbox with the text beside it, so Matthew picks the ones he likes.
 *
 * ‼️ BUILT FROM kit PRIMITIVES RATHER THAN ADDED TO kit.ts. There is no checkbox in the kit and
 * this is the only document that wants one; kit.ts belongs to no lane and the presence and
 * cleanup PDFs are being edited in parallel, so a new export there is a merge conflict over
 * fourteen lines. It uses the kit's own margins, palette and paragraph layout, so it is not a
 * second PDF style — it is the kit's style with a square in front of it.
 */
function checkboxLine(state: PageState, text: string, opts?: { size?: number }): void {
  const size = opts?.size ?? 9.5;
  const box = 3.2;
  ensureSpace(state, size * 0.48 + 3);

  const top = state.y;
  setColor(state.doc, "draw", CARD_BORDER);
  state.doc.setLineWidth(0.3);
  state.doc.rect(MARGIN, top + 1.2, box, box, "S");

  paragraph(state, text, { size, x: MARGIN + box + 3, width: CONTENT_W - box - 3, gap: 1.6 });
}

/** The hard divider. Everything below it waits for the card. */
function divider(state: PageState, label: string): void {
  ensureSpace(state, 14);
  setColor(state.doc, "draw", RED);
  state.doc.setLineWidth(0.8);
  state.doc.line(MARGIN, state.y, PAGE_W - MARGIN, state.y);
  state.y += 5;
  paragraph(state, label, { bold: true, size: 12, color: RED });
}

export interface CallQuestionsData {
  clientName: string;
  facts: QuestionFacts;
  questions: DraftedQuestion[];
  after: AfterTheCard;
}

/**
 * The technical asks, and every one of them is a value we already hold.
 *
 * ‼️ BUILT IN CODE, NOT BY THE MODEL, AND THAT IS THE POINT OF THE SPLIT.
 * "Who manages your DNS?" is a question the record already answers, and a model asked to write
 * it produces a worse version of a sentence we can print exactly: "your DNS is at GoDaddy, so
 * that is Domains, DNS, Manage Zones". Same reason buildCoachNotes() is assembled by hand.
 */
export interface AfterTheCard {
  funnel: string[];
  presence: string[];
  technical: string[];
  reviews: string[];
}

export function buildAfterTheCard(args: {
  facts: QuestionFacts;
  domain: string | null;
  hubHost: string | null;
  reviewsHost: string | null;
  cnameTarget: string | null;
  searchConsoleTxt: string | null;
  bookingSoftware: string | null;
  reviewMode: string | null;
  reviewOwner: string | null;
}): AfterTheCard {
  const { facts } = args;
  const clickPath = clickPathFor(facts.technical.dnsProvider, args.domain ?? "");

  return {
    funnel: [
      "Where does an enquiry land today: a form, the phone, a DM, or somewhere else?",
      "Who answers it, and how quickly, on a normal weekday?",
      args.bookingSoftware
        ? `The record says you book through ${args.bookingSoftware}. Is that still what you use?`
        : "What software do you book with? Nothing was recorded at intake.",
      "What happens to an enquiry that does not book on the first contact?",
    ],
    presence: [
      "Google Business Profile: who owns the login today, and is it claimed?",
      ...(facts.presence.coreMismatch.length
        ? [
            `These disagree with your canonical record and need a login each: ${facts.presence.coreMismatch.join(", ")}. Who holds them?`,
          ]
        : []),
      ...(facts.presence.coreMissing.length
        ? [`No listing was found on ${facts.presence.coreMissing.join(", ")}. Was one ever created?`]
        : []),
      ...(facts.presence.coreNotChecked.length
        ? [
            `Still unchecked, so nothing is claimed about them either way: ${facts.presence.coreNotChecked.join(", ")}.`,
          ]
        : []),
    ],
    technical: [
      facts.technical.dnsProvider
        ? `DNS is managed at ${facts.technical.dnsProvider}${clickPath ? `: ${clickPath}` : ""}. Who can log in there right now?`
        : "We could not identify who manages your DNS. Read the nameservers out and let them recognise the company.",
      ...(facts.technical.registrar
        ? [`The domain is registered with ${facts.technical.registrar}. Same login, or a different one?`]
        : []),
      args.hubHost && args.cnameTarget
        ? `CNAME  ${args.hubHost}  ->  ${args.cnameTarget}`
        : "The hub CNAME is not seeded yet, so there is no value to read out.",
      args.reviewsHost && args.cnameTarget
        ? `CNAME  ${args.reviewsHost}  ->  ${args.cnameTarget}`
        : "The reviews CNAME is not seeded yet.",
      args.domain
        ? `TXT    ${args.domain}  ->  ${args.searchConsoleTxt ?? "generated in Search Console on the call"}`
        : "No domain on the record, so no TXT record can be composed.",
      "Search Console: is the domain already verified, and by whom?",
      "Analytics: does one exist, and who is the account owner?",
      "Never ask for registrar credentials. They drive, you read the values out.",
    ],
    reviews: [
      args.reviewMode
        ? `The record says reviews are requested by ${args.reviewMode}. Confirm that is still true.`
        : "How are reviews asked for today: automatically through the booking software, or by hand?",
      args.reviewOwner
        ? `${args.reviewOwner} is the named person on the record. Still the right one?`
        : "Who is the one NAMED person who will hand out the cards? A name, not the front desk.",
      "Which review page do you want customers sent to, and can you paste the link?",
    ],
  };
}

export function renderCallQuestions(d: CallQuestionsData): Buffer {
  const state = startDoc({
    title: `${d.clientName} — closing questions (internal)`,
    footer: plainFooter(
      "SRT internal · not for the client · every figure from this client's own reports"
    ),
  });

  coverHeading(state, {
    eyebrow: "Closing questions · internal",
    title: d.clientName,
    subtitle:
      "Pick the ones you want. Ordered by CLOSER, which is the same spine the live coach runs on.",
  });

  paragraph(
    state,
    d.facts.score === null
      ? "No baseline score exists for this client, so nothing below cites one."
      : `Built from this client's own reports: score ${d.facts.score} of 100, absent from ${d.facts.absentPrompts.length} of the questions their buyers ask, ${d.facts.namedInstead.length} businesses named instead.`,
    { color: MUTED, size: 9 }
  );

  for (const section of CLOSER_SECTIONS) {
    const list = d.questions.filter((q) => q.section === section.key);
    if (!list.length) continue;
    ensureSpace(state, 26);
    sectionHeading(state, `${section.letter} · ${section.title} — ${list.length}`);
    paragraph(state, section.purpose, { color: MUTED, size: 8.5 });
    for (const q of list) checkboxLine(state, q.question);
  }

  // ‼️ THE DIVIDER AND ITS OWN PAGE ARE THE WHOLE POINT OF THE SECOND HALF.
  // Matthew: "we cant capture all of this if they are not willing to put a card on file."
  // Nothing below is asked before the commitment, and putting it on the same page as the closing
  // questions is how it gets asked early.
  newPage(state);
  divider(state, "AFTER THE CARD");
  paragraph(
    state,
    "None of this is asked before the commitment. A client who has not committed does not hand over their Google account, and asking early is how a call ends with neither.",
    { bold: true, size: 10, color: AMBER }
  );
  paragraph(
    state,
    "Every value below is already on the record. Read them out; do not ask a question this document can answer.",
    { color: MUTED, size: 8.5 }
  );

  const blocks: Array<[string, string[]]> = [
    ["The funnel", d.after.funnel],
    ["Online presence and the GBP", d.after.presence],
    ["Search Console, Analytics and DNS", d.after.technical],
    ["The review workflow", d.after.reviews],
  ];

  for (const [title, items] of blocks) {
    if (!items.length) continue;
    ensureSpace(state, 24);
    sectionHeading(state, title);
    for (const item of items) checkboxLine(state, item, { size: 9 });
  }

  ensureSpace(state, 20);
  paragraph(state, "Anything they say here goes on the call sheet's capture page before you hang up.", {
    color: REEF,
    size: 9,
  });

  return finishDoc(state);
}

// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generate the closing questions and file them against step 20.
 *
 * Called from the `call_sheet` runner, so it runs when step 18 completes. It stores and records
 * and posts NOTHING — see the file header for why, and step-engine.ts's `call_held` card for
 * where it surfaces.
 */
export async function generateCallQuestions(clientId: string): Promise<AutoResult> {
  const facts = await buildQuestionFacts(clientId);
  if (!facts) return { ok: false, error: "client not found" };

  if (facts.score === null && !facts.absentPrompts.length) {
    // ‼️ REFUSES RATHER THAN WRITING GENERIC QUESTIONS. Matthew asked for questions "based on the
    // report we did", and with no report this would be thirty-three sales questions anybody could
    // have written, handed over in a document whose cover says they came from his own data.
    return {
      ok: false,
      error:
        "No baseline measurement for this client, so there is nothing to build closing questions " +
        "from. Confirm the baseline scan (step 2) first.",
    };
  }

  let questions: DraftedQuestion[];
  try {
    questions = await draftClosingQuestions(facts);
  } catch (e) {
    return { ok: false, error: `drafting the closing questions failed: ${(e as Error).message}` };
  }

  const { data: client } = await supabaseAdmin
    .from("clients")
    .select("domain, subdomain, booking_software, review_request_mode, review_owner_name")
    .eq("id", clientId)
    .maybeSingle();

  const domain = (client?.domain as string | null) ?? null;
  const { subdomainLabel } = await import("../normalize");
  const label = domain ? subdomainLabel((client?.subdomain as string | null) ?? "learn", domain) : null;

  const dnsRows = await loadDnsRows(clientId);
  const cname = dnsRows.find((r) => r.record_type === "CNAME");
  const txt = dnsRows.find((r) => r.record_type === "TXT");

  const after = buildAfterTheCard({
    facts,
    domain,
    hubHost: domain && label ? `${label}.${domain}` : null,
    reviewsHost: domain ? `reviews.${domain}` : null,
    // ‼️ THE SEEDED VALUE OR NOTHING. HUB_CNAME_TARGET's default is measured WRONG for this
    // project (Vercel issues per-domain targets), and a wrong value on a page somebody reads
    // down the phone is worse than a line saying it is not seeded yet.
    cnameTarget: (cname?.value as string | null) ?? null,
    searchConsoleTxt: (txt?.value as string | null) ?? null,
    bookingSoftware: (client?.booking_software as string | null) ?? null,
    reviewMode: (client?.review_request_mode as string | null) ?? null,
    reviewOwner: (client?.review_owner_name as string | null) ?? null,
  });

  let buffer: Buffer;
  try {
    buffer = renderCallQuestions({ clientName: facts.clientName, facts, questions, after });
  } catch (e) {
    return { ok: false, error: `render failed: ${(e as Error).message}` };
  }

  const stored = await storeGeneratedDoc({
    clientId,
    stepKey: "call_held",
    filename: `Closing questions (internal) - ${facts.clientName}.pdf`,
    buffer,
  });

  if (!stored.ok || !stored.docId) {
    return { ok: false, error: stored.error ?? "storing the closing questions failed" };
  }

  // The step's durable pointer to what it has waiting for it. Step 20's card reads this back
  // through outputRefsFor and links it; nothing is posted here.
  const { error } = await supabaseAdmin
    .from("client_delivery_steps")
    .update({ output_ref: stored.docId, updated_at: new Date().toISOString() })
    .eq("client_id", clientId)
    .eq("step_key", "call_held");

  if (error) {
    return { ok: false, error: `filing it against step 20 failed: ${error.message}` };
  }

  return {
    ok: true,
    docId: stored.docId,
    note: `${questions.length} closing questions filed against the call, waiting on step 20's card.`,
  };
}
