// The findings report — delivery step 10, Runner v3 section 10, Artifact Templates section 2.
//
// This is the document the whole onboarding exists to produce. Six sections, in that order, no
// deviation. It is assembled from what steps 2 to 4c already wrote; it computes nothing new and
// invents nothing at all.
//
//   1 Where AI names other clinics in {city} instead of you
//   2 Why — presence and NAP
//   3 The review gap
//   4 The technical gap
//   5 The plan for the next 21 days
//   6 What we need from you
//
// ‼️ SECTION 5 IS A PLAN, NEVER A PRICED FIX LIST, AND FOR A PILOT NOTHING PURCHASABLE APPEARS
// IN IT AT ALL. Runner v3 section 10 and Artifact Templates section 2 both say it, and the
// pilot doc is the reason: these clinics are getting the service free so the case study measures
// the product. A price in this section turns a diagnostic into a pitch and makes every number
// above it look like a sales argument rather than a measurement.
//
// ‼️ VOCABULARY. named / not named / named alongside / named instead. Never ranked, position,
// #N or top result. The kit exports the four words so they are not retyped.
//
// ‼️ audit_runs.prompt IS THE QUESTION AS RUN AND IS THE ONLY THING QUOTED HERE.
// audit_reports.prompts is REGENERATED by every run, so quoting it would let a later audit
// silently rewrite the questions in a report already sent to a client.

import { supabaseAdmin } from "@/lib/db";
import { canonicalFor, loadSweep, effectiveStatus, countByStatus } from "../presence-sweep";
import { platformByKey } from "@/config/presence-platforms";
import type { Canonical } from "../nap-compare";
import { selectedCompetitors, tallyRecommended, type CandidateRow } from "../competitors";
import { loadReviewAudit, isRecorded, reviewPlatformLabel, type ReviewAuditRow } from "../review-audit";
import type { SiteIntel } from "../site-intel";
import { signedDocUrl } from "../onboarding-docs";
import {
  startDoc,
  finishDoc,
  coverHeading,
  sectionHeading,
  paragraph,
  bulletList,
  keyValueTable,
  image,
  ensureSpace,
  fidelityFooter,
  MUTED,
  AMBER,
  REEF,
  RED,
  NAMED_INSTEAD,
  type PageState,
  type TableRow,
} from "@/lib/pdf/kit";
import { deliverArtifact } from "./deliver";

interface RunRow {
  prompt: string;
  engine: string;
  mentioned: boolean | null;
  recommended: string[];
}

const ENGINE_LABEL: Record<string, string> = {
  openai: "ChatGPT",
  chatgpt_web: "ChatGPT",
  perplexity: "Perplexity",
  gemini: "Gemini",
};

// ─────────────────────────────────────────────────────────────────────────────
// 1 · Where AI names other clinics instead of you
// ─────────────────────────────────────────────────────────────────────────────

/**
 * ‼️ HOW THE HEADLINE ROLLS UP, STATED BECAUSE RUNNER V3 SECTION 4 ASKED TO BE TOLD.
 *
 * Artifact Templates section 3 does not define how several engines collapse into one
 * "named in X of 20". Section 4 says: if it does not, define it as "named by at least one
 * engine", always print the per-engine grid underneath, and say you had to define it. That is
 * what this does, and the definition is printed on the page rather than left in code.
 *
 * A question with `mentioned === null` was never measured and is NOT counted as "not named".
 * Those are different claims: one is about what an engine said, the other about what we ran.
 */
function namedCount(runs: RunRow[]): { named: number; measured: number; unmeasured: number } {
  const byPrompt = new Map<string, boolean | null>();
  for (const r of runs) {
    const current = byPrompt.get(r.prompt);
    if (r.mentioned === true) byPrompt.set(r.prompt, true);
    else if (current === undefined) byPrompt.set(r.prompt, r.mentioned);
  }
  let named = 0;
  let unmeasured = 0;
  for (const v of byPrompt.values()) {
    if (v === true) named += 1;
    else if (v === null) unmeasured += 1;
  }
  return { named, measured: byPrompt.size - unmeasured, unmeasured };
}

function perEngineGrid(runs: RunRow[]): TableRow[] {
  const byEngine = new Map<string, { named: number; total: number }>();
  for (const r of runs) {
    if (r.mentioned === null) continue;
    const e = byEngine.get(r.engine) ?? { named: 0, total: 0 };
    e.total += 1;
    if (r.mentioned) e.named += 1;
    byEngine.set(r.engine, e);
  }
  return [...byEngine.entries()].map(([engine, v]) => ({
    label: ENGINE_LABEL[engine] ?? engine,
    value: `named in ${v.named} of ${v.total}`,
    tone: v.named === 0 ? "bad" : v.named < v.total / 2 ? "warn" : "good",
  }));
}

async function screenshotBytes(docId: string): Promise<Buffer | null> {
  try {
    const url = await signedDocUrl(docId);
    if (!url) return null;
    const res = await fetch(url);
    if (!res.ok) return null;
    return Buffer.from(await res.arrayBuffer());
  } catch {
    return null;
  }
}

async function sectionOne(
  state: PageState,
  args: { city: string; clientName: string; runs: RunRow[]; aliases: string[]; screenshotIds: string[] }
) {
  sectionHeading(state, `Where AI names other clinics in ${args.city} instead of you`, { number: 1 });

  const { named, measured, unmeasured } = namedCount(args.runs);
  const total = measured + unmeasured;

  paragraph(
    state,
    `When somebody in ${args.city} asks an AI assistant the kinds of questions your patients ask, you are named in ${named} of ${total}.`,
    { bold: true, size: 12, color: named === 0 ? RED : AMBER }
  );

  if (unmeasured > 0) {
    paragraph(
      state,
      `${unmeasured} of those ${total} could not be measured and are not counted either way.`,
      { color: MUTED, size: 9 }
    );
  }

  paragraph(
    state,
    'Counted as named when at least one engine named you. The per-engine breakdown is below, so you can see exactly where that count comes from.',
    { color: MUTED, size: 8.5 }
  );

  keyValueTable(state, perEngineGrid(args.runs), { labelWidth: 60 });

  // Screenshots of the real answers. Printed before the tally, because a client believes a
  // screenshot of their own question being answered with somebody else's name in a way no
  // number achieves.
  for (const id of args.screenshotIds.slice(0, 5)) {
    image(state, await screenshotBytes(id), {
      maxH: 85,
      caption: "The answer as it appeared, unedited.",
      fallbackLabel: "Screenshot on file",
    });
  }

  const tallies = tallyRecommended(args.runs, args.aliases);
  if (tallies.length) {
    paragraph(state, `Who was ${NAMED_INSTEAD}`, { bold: true, size: 10.5 });
    keyValueTable(
      state,
      tallies.slice(0, 8).map((t) => ({
        label: t.name,
        value: `named in ${t.timesNamed} of ${total}`,
        tone: "warn" as const,
      })),
      { labelWidth: 80 }
    );
    paragraph(
      state,
      "These are the businesses an assistant puts in front of somebody who never typed a business name at all.",
      { color: MUTED, size: 9 }
    );
  } else {
    paragraph(state, "No competing business was named consistently enough to list.", { color: MUTED });
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// 2 · Why
// ─────────────────────────────────────────────────────────────────────────────

function sectionTwo(
  state: PageState,
  args: { canonical: Canonical; rows: Awaited<ReturnType<typeof loadSweep>>; presenceDocUrl: string | null }
) {
  sectionHeading(state, "Why", { number: 2 });

  const core = args.rows.filter((r) => r.tier === "core_six");
  const coreCounts = countByStatus(core);

  const variants = new Set(
    args.rows
      .filter((r) => r.rawAddress)
      .map((r) => (r.rawAddress ?? "").toLowerCase().replace(/\s+/g, " ").trim())
  );

  if (variants.size > 1) {
    paragraph(
      state,
      `Your address appears ${variants.size} different ways across the platforms we checked. An assistant trying to confirm who you are finds several answers and trusts none of them.`,
      { size: 10.5, bold: true }
    );
  } else {
    paragraph(
      state,
      "An assistant confirms a business by finding the same name, address and phone in several independent places. Where those records disagree, it cannot confirm you exist as one business.",
      { size: 10 }
    );
  }

  paragraph(state, "The core six — the records the engines lean on hardest", { bold: true, size: 10 });
  keyValueTable(
    state,
    core.map((r) => {
      const status = effectiveStatus(r);
      return {
        label: platformByKey(r.platform)?.label ?? r.platform,
        value:
          status === "match"
            ? "matches your record"
            : status === "mismatch"
              ? `does not match: ${r.rawAddress ?? r.rawPhone ?? r.rawName ?? "see report"}`
              : status === "duplicate"
                ? "more than one live listing"
                : status === "missing"
                  ? "no listing found"
                  : "not checked",
        tone:
          status === "match" ? ("good" as const) : status === "not_checked" ? ("normal" as const) : ("warn" as const),
      };
    }),
    { labelWidth: 60 }
  );

  // ‼️ Never "no issues found". If it was not checked, the document says it was not checked.
  if (coreCounts.not_checked) {
    paragraph(
      state,
      `${coreCounts.not_checked} of the core six have not been checked yet. That is not a finding that they are correct.`,
      { color: AMBER, bold: true, size: 9.5 }
    );
  }

  const extendedCounts = countByStatus(args.rows.filter((r) => r.tier === "extended"));
  paragraph(
    state,
    `Twelve smaller directories were also reviewed for context: ${extendedCounts.match} match, ${extendedCounts.mismatch} do not, ${extendedCounts.missing} have no listing, ${extendedCounts.not_checked} not checked. These matter less and are not part of the first three weeks of work.`,
    { color: MUTED, size: 9 }
  );

  if (args.presenceDocUrl) {
    paragraph(state, `The full record, platform by platform, with screenshots: ${args.presenceDocUrl}`, {
      color: REEF,
      size: 9,
    });
  }

}

// ─────────────────────────────────────────────────────────────────────────────
// 3 · The review gap
// ─────────────────────────────────────────────────────────────────────────────

function sectionThree(
  state: PageState,
  args: { clientName: string; competitors: CandidateRow[]; reviewRows: ReviewAuditRow[] }
) {
  sectionHeading(state, "The review gap", { number: 3 });

  if (!args.competitors.length) {
    paragraph(
      state,
      "Three competitors have not been selected yet, so there is nothing to compare against here. This section is written once that choice is made.",
      { color: AMBER }
    );
    return;
  }

  paragraph(
    state,
    "Assistants read reviews the way a person does: they look for what patients actually said, not how many stars were clicked.",
    { size: 10 }
  );

  keyValueTable(
    state,
    args.competitors.map((c) => ({
      label: c.name,
      value: c.timesNamed > 0 ? `named in ${c.timesNamed} of the questions we ran` : "named by you at intake",
      tone: "warn" as const,
    })),
    { labelWidth: 80 }
  );

  reviewTable(state, args.clientName, args.reviewRows);
}

/**
 * The review numbers, or an honest account of why they are not here.
 *
 * ‼️ AN UNRECORDED ROW PRINTS "not recorded", NEVER 0 AND NEVER A BLANK CELL.
 * `review_audit_rows.review_count` is null until a person types a number, and this is the
 * document where that distinction has to survive: a client reading "0" next to their own name
 * on Google concludes something very specific and very wrong. Same rule the presence PDF
 * enforces one section up, for the same reason.
 */
function reviewTable(state: PageState, clientName: string, rows: ReviewAuditRow[]) {
  if (!rows.length) {
    paragraph(
      state,
      "The review audit has not been seeded yet, so there are no numbers to print here. It is a manual read: no review provider is keyed, so somebody reads each listing and records what it says.",
      { color: AMBER, size: 9 }
    );
    return;
  }

  const recorded = rows.filter(isRecorded);
  if (!recorded.length) {
    paragraph(
      state,
      `All ${rows.length} rows are still outstanding. Nothing below claims these businesses have no reviews. It claims nobody has read them yet.`,
      { color: AMBER, bold: true, size: 9.5 }
    );
    return;
  }

  if (recorded.length < rows.length) {
    paragraph(
      state,
      `${rows.length - recorded.length} of ${rows.length} rows have not been read yet and are shown as "not recorded". That is not a finding that the listing is empty.`,
      { color: AMBER, size: 9.5 }
    );
  }

  // Grouped by subject so the client's line sits above the three it is being compared with,
  // which is the comparison this section exists to make.
  const bySubject = new Map<string, ReviewAuditRow[]>();
  for (const r of rows) {
    const list = bySubject.get(r.subjectName) ?? [];
    list.push(r);
    bySubject.set(r.subjectName, list);
  }

  // The client first, whoever they sort as.
  const ordered = [...bySubject.entries()].sort((a, b) =>
    a[0] === clientName ? -1 : b[0] === clientName ? 1 : a[0].localeCompare(b[0])
  );

  for (const [subject, list] of ordered) {
    ensureSpace(state, 22);
    paragraph(state, subject === clientName ? `${subject} (you)` : subject, { bold: true, size: 10 });
    keyValueTable(
      state,
      list.map((r) => ({
        label: reviewPlatformLabel(r.platform),
        value: !isRecorded(r)
          ? "not recorded"
          : [
              `${r.reviewCount} reviews`,
              r.averageRating !== null ? `${r.averageRating} avg` : null,
              r.mostRecentReviewAt ? `most recent ${r.mostRecentReviewAt.slice(0, 10)}` : null,
              r.ownerResponseRate !== null ? `${Math.round(r.ownerResponseRate * 100)}% answered` : null,
            ]
              .filter(Boolean)
              .join(" · "),
        tone: !isRecorded(r) ? ("normal" as const) : subject === clientName ? ("normal" as const) : ("warn" as const),
      })),
      { labelWidth: 60, size: 8.5 }
    );

    const themes = list.flatMap((r) => r.negativeThemes).filter(Boolean);
    if (themes.length) {
      bulletList(state, [...new Set(themes)].slice(0, 6), { size: 8.5 });
    }
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// 4 · The technical gap
// ─────────────────────────────────────────────────────────────────────────────

function sectionFour(
  state: PageState,
  args: { intel: SiteIntel | null; robots: unknown; signals: Array<{ kind: string; detail: string }> }
) {
  sectionHeading(state, "The technical gap", { number: 4 });
  paragraph(state, "One line each. No jargon.", { color: MUTED, size: 9 });

  const lines: string[] = [];

  if (args.intel) {
    const i = args.intel;
    if (i.resolverHealthy) {
      lines.push(
        i.dnsProvider
          ? `Your DNS is managed at ${i.dnsProvider}. That is where the three records go on the call.`
          : `Your DNS is on nameservers we do not recognise (${i.nameservers.join(", ") || "none found"}). We will read them to you rather than guess.`
      );
      if (i.mailProvider) lines.push(`Your email runs on ${i.mailProvider}.`);
    } else {
      lines.push("The DNS lookup did not complete, so nothing here is claimed about your DNS.");
    }

    if (i.registration.registrar) {
      lines.push(`Your domain is registered with ${i.registration.registrar}.`);
    }
    if (i.hosting.networkOrg || i.hosting.cdn) {
      lines.push(
        `Your website is hosted on ${i.hosting.networkOrg ?? "a network we could not identify"}${
          i.hosting.cdn ? `, served through ${i.hosting.cdn}` : ""
        }.`
      );
    }
    lines.push(
      i.cms
        ? `Your site is built on ${i.cms}.`
        : "We could not identify what your site is built on from its markup."
    );
  } else {
    lines.push("The site and hosting check has not run yet, so this section is incomplete.");
  }

  for (const s of args.signals) {
    lines.push(s.detail);
  }

  // The robots finding is the one with real teeth: a site that blocks the AI crawlers by name
  // cannot be quoted by them no matter what else is fixed.
  const robots = args.robots as Array<{ bot: string; engine: string; role: string }> | null;
  if (robots === null) {
    lines.push("We could not read your robots.txt, so nothing is claimed about crawler access.");
  } else if (robots.length === 0) {
    lines.push("Your robots.txt does not block the AI crawlers.");
  } else {
    const searchBots = robots.filter((r) => r.role === "search");
    if (searchBots.length) {
      lines.push(
        `Your site blocks ${searchBots.map((r) => r.engine).join(", ")} by name. Those assistants cannot read your pages at all.`
      );
    }
  }

  bulletList(state, lines);
}

// ─────────────────────────────────────────────────────────────────────────────
// 5 · The plan
// ─────────────────────────────────────────────────────────────────────────────

/**
 * ‼️ NOTHING PURCHASABLE. NO PRICES. NO PACKAGES. NO UPGRADE PATHS. NO "STARTING AT".
 * Runner v3 section 10 and Artifact Templates section 2. This is a plan of work, and for a pilot
 * client the work is already free, so a price here would be both wrong and confusing.
 */
function sectionFive(state: PageState, args: { clientName: string; hasCoreIssues: boolean }) {
  sectionHeading(state, "The plan for the next 21 days", { number: 5 });

  paragraph(state, "Week one", { bold: true, size: 10.5, gap: 1 });
  bulletList(state, [
    "Lock your name, address and phone to one exact wording, confirmed with you on the call.",
    args.hasCoreIssues
      ? "Correct the core six records that disagree with it, starting with any duplicate listing."
      : "Confirm the core six records against that wording, one platform at a time.",
    "Take the day-zero measurement, so everything after this is measured against a fixed starting point.",
  ]);

  paragraph(state, "Week two", { bold: true, size: 10.5, gap: 1 });
  bulletList(state, [
    "Build out your Google Business Profile: categories, services, photos, and answers to the questions patients actually ask.",
    "Stand up your answer pages on your own domain, written from the questions we measured.",
    "Put the review cards in your hands so patients can describe their visit in their own words.",
  ]);

  paragraph(state, "Week three", { bold: true, size: 10.5, gap: 1 });
  bulletList(state, [
    "Publish the first set of answer pages and confirm the assistants can read them.",
    "Work through the smaller directories that disagree with your record.",
    "First weekly report, then the day-30 measurement against day zero.",
  ]);

  paragraph(
    state,
    "You will get a report at day 30, day 60 and day 90 showing what moved and what did not. A flat month is reported as a flat month.",
    { color: MUTED, size: 9 }
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// 6 · What we need from you
// ─────────────────────────────────────────────────────────────────────────────

/** The access list. ONLY the access list. Nothing is sold, asked or explained here. */
function sectionSix(state: PageState, args: { intel: SiteIntel | null; domain: string }) {
  sectionHeading(state, "What we need from you", { number: 6 });

  bulletList(state, [
    "Manager access to your Google Business Profile.",
    "Access to Google Search Console for your domain, or permission to set it up.",
    "Viewer or editor access to Google Analytics, if you have it.",
    "Three DNS records added at your domain. Two CNAMEs and one TXT. We read them to you on the call and you type them in.",
    "The name of one person at the clinic who will hand out the review cards.",
  ]);

  if (args.intel?.dnsProvider && args.intel.clickPath) {
    paragraph(
      state,
      `Your DNS is at ${args.intel.dnsProvider}, so for the records that is: ${args.intel.clickPath}.`,
      { color: MUTED, size: 9 }
    );
  }

  paragraph(state, "We never ask for your registrar password, and we never log in as you.", {
    color: MUTED,
    size: 9,
  });
}

// ─────────────────────────────────────────────────────────────────────────────

export async function generateFindings(
  clientId: string
): Promise<{ ok: boolean; error?: string; docId?: string }> {
  const { data: client } = await supabaseAdmin
    .from("clients")
    .select("id, legal_name, dba_name, city, state, domain, website, site_intel")
    .eq("id", clientId)
    .maybeSingle();

  if (!client) return { ok: false, error: "client not found" };

  const canonical = await canonicalFor(clientId);
  if (!canonical) return { ok: false, error: "no canonical record" };

  const { data: report } = await supabaseAdmin
    .from("audit_reports")
    .select("id, engines, robots_check, site_signals")
    .eq("client_id", clientId)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  if (!report) {
    return { ok: false, error: "no baseline run for this client, so section 1 has nothing to report" };
  }

  const { data: runRows } = await supabaseAdmin
    .from("audit_runs")
    .select("prompt, engine, mentioned, recommended")
    .eq("report_id", report.id);

  const runs: RunRow[] = (runRows ?? []).map((r) => ({
    prompt: r.prompt as string,
    engine: r.engine as string,
    mentioned: (r.mentioned as boolean | null) ?? null,
    recommended: (r.recommended as string[] | null) ?? [],
  }));

  const rows = await loadSweep(clientId);
  const competitors = await selectedCompetitors(clientId);
  const reviewRows = await loadReviewAudit(clientId);

  // Screenshots filed against the baseline step are section 1's evidence.
  const { data: shots } = await supabaseAdmin
    .from("client_docs")
    .select("id, content_type")
    .eq("client_id", clientId)
    .eq("delivery_step_key", "baseline_scan")
    .eq("source", "slack")
    .limit(5);

  const { data: presenceDoc } = await supabaseAdmin
    .from("client_docs")
    .select("id")
    .eq("client_id", clientId)
    .eq("delivery_step_key", "presence_pdf")
    .eq("source", "generated")
    .order("uploaded_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  const { data: versions } = await supabaseAdmin
    .from("question_set_versions")
    .select("version")
    .eq("vertical", "med_spa");

  const clientName = ((client.dba_name || client.legal_name) as string) ?? "";
  const city = [client.city, client.state].filter(Boolean).join(", ") || "your area";
  const appBase = process.env.NEXT_PUBLIC_APP_URL || "https://mission.srtagency.com";

  const state = startDoc({
    title: `${clientName} — findings`,
    footer: fidelityFooter({
      questions: new Set(runs.map((r) => r.prompt)).size,
      engines: ((report.engines as string[] | null) ?? ["chatgpt_web"]),
      date: new Date(),
      questionSetVersions: (versions ?? []).map((v) => v.version as string),
    }),
  });

  coverHeading(state, {
    eyebrow: "Findings",
    title: clientName,
    subtitle: `What AI assistants currently say when somebody in ${city} asks for a clinic like yours, and why.`,
  });

  await sectionOne(state, {
    city,
    clientName,
    runs,
    aliases: [client.legal_name as string, client.dba_name as string].filter(Boolean),
    screenshotIds: (shots ?? []).map((s) => s.id as string),
  });

  sectionTwo(state, {
    canonical,
    rows,
    presenceDocUrl: presenceDoc ? `${appBase}/api/clients/${clientId}/docs/${presenceDoc.id}` : null,
  });

  sectionThree(state, { clientName, competitors, reviewRows });

  sectionFour(state, {
    intel: (client.site_intel as SiteIntel | null) ?? null,
    robots: report.robots_check,
    signals: ((report.site_signals as Array<{ kind: string; detail: string }> | null) ?? []),
  });

  sectionFive(state, {
    clientName,
    hasCoreIssues: rows.some(
      (r) => r.tier === "core_six" && ["mismatch", "duplicate", "missing"].includes(effectiveStatus(r))
    ),
  });

  sectionSix(state, {
    intel: (client.site_intel as SiteIntel | null) ?? null,
    domain: (client.domain as string) ?? "",
  });

  const buffer = finishDoc(state);

  const { named, measured, unmeasured } = namedCount(runs);
  const notChecked = countByStatus(rows).not_checked;

  const message = [
    `:page_facing_up: Findings for *${clientName}*. Named in ${named} of ${measured + unmeasured}.`,
    notChecked ? `:warning: ${notChecked} platforms are still "not checked" and the PDF says so.` : "",
    competitors.length === 0 ? ":warning: No competitors selected, so section 3 is a placeholder." : "",
    `Fidelity: ${((report.engines as string[] | null) ?? ["chatgpt_web"]).length} engine. Read it before it goes anywhere near the client.`,
  ]
    .filter(Boolean)
    .join("\n");

  const result = await deliverArtifact({
    clientId,
    stepKey: "findings_doc",
    filename: `Findings - ${clientName}.pdf`,
    buffer,
    message,
  });

  return { ok: result.ok, error: result.error, docId: result.docId };
}
